#!/bin/sh
#
# mmd2oepub --- MultiMarkdown convenience script
#	<http://fletcherpenney.net/multimarkdown/>
#	Fletcher T. Penney
#
# Pass arguments on to the binary to convert text to EPUB 3
#

# Be sure to include multimarkdown in our PATH
export PATH="$PWD:/usr/local/bin:$PATH"

if ! command -v multimarkdown >/dev/null 2>&1
then
	echo multimarkdown executable not found! >&2
	exit 1
fi

if [ $# = 0 ]
then
	multimarkdown -t epub
else
until [ "$*" = "" ]
do
	multimarkdown -b -t epub "$1"
	shift
done
fi
