/* Generated by re2c 0.14.3 on Tue Mar 28 08:27:15 2017 */
/**

	MultiMarkdown 6 -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file lexer.re

	@brief Description of the regular expressions used to define tokens, 
	used by re2c to create a lexer/tokenizer.


	@author	Fletcher T. Penney
	@bug	

**/

/*

	Copyright © 2016 - 2017 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..
	
	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:
	
		https://github.com/fletcher/MultiMarkdown-4/
	
	MMD 4 is released under both the MIT License and GPL.
	
	
	CuTest is released under the zlib/libpng license. See CuTest.c for the text
	of the license.
	
	
	## The MIT License ##
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

*/

#include "lexer.h"
#include "libMultiMarkdown.h"
#include "parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int scan(Scanner * s, const char * stop) {

	scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;

	
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	yych = *YYCURSOR;
	switch (yych) {
	case '\t':	goto yy46;
	case '\n':	goto yy55;
	case '\r':	goto yy57;
	case ' ':	goto yy48;
	case '!':	goto yy20;
	case '"':	goto yy29;
	case '#':	goto yy50;
	case '$':	goto yy42;
	case '%':	goto yy52;
	case '&':	goto yy36;
	case '\'':	goto yy31;
	case '(':	goto yy21;
	case ')':	goto yy23;
	case '*':	goto yy58;
	case '+':	goto yy6;
	case '-':	goto yy8;
	case '.':	goto yy33;
	case '/':	goto yy38;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy54;
	case ':':	goto yy34;
	case '<':	goto yy10;
	case '=':	goto yy14;
	case '>':	goto yy25;
	case '[':	goto yy16;
	case '\\':	goto yy40;
	case ']':	goto yy18;
	case '^':	goto yy44;
	case '_':	goto yy60;
	case '`':	goto yy62;
	case '{':	goto yy4;
	case '|':	goto yy64;
	case '}':	goto yy27;
	case '~':	goto yy12;
	case 0xA0:	goto yy49;
	case 0xC3:	goto yy2;
	default:	goto yy66;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 0xA0:	goto yy285;
	default:	goto yy3;
	}
yy3:
	{ goto scan; }
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy268;
	case '-':	goto yy267;
	case '=':	goto yy264;
	case '>':	goto yy266;
	case '{':	goto yy262;
	case '~':	goto yy265;
	default:	goto yy5;
	}
yy5:
	{ return TEXT_BRACE_LEFT; }
yy6:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy259;
	default:	goto yy7;
	}
yy7:
	{ return PLUS; }
yy8:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy253;
	default:	goto yy9;
	}
yy9:
	{ return DASH_N; }
yy10:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '<':	goto yy250;
	default:	goto yy11;
	}
yy11:
	{ return ANGLE_LEFT; }
yy12:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '>':	goto yy246;
	case '~':	goto yy245;
	default:	goto yy13;
	}
yy13:
	{ return SUBSCRIPT; }
yy14:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy242;
	default:	goto yy15;
	}
yy15:
	{ return EQUAL; }
yy16:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '#':	goto yy238;
	case '%':	goto yy232;
	case '>':	goto yy240;
	case '?':	goto yy234;
	case '^':	goto yy236;
	default:	goto yy17;
	}
yy17:
	{ return BRACKET_LEFT; }
yy18:
	++YYCURSOR;
	{ return BRACKET_RIGHT; }
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case '[':	goto yy230;
	default:	goto yy3;
	}
yy21:
	++YYCURSOR;
	{ return PAREN_LEFT; }
yy23:
	++YYCURSOR;
	{ return PAREN_RIGHT; }
yy25:
	++YYCURSOR;
	{ return ANGLE_RIGHT; }
yy27:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '}':	goto yy228;
	default:	goto yy28;
	}
yy28:
	{ return TEXT_BRACE_RIGHT; }
yy29:
	++YYCURSOR;
	{ return QUOTE_DOUBLE; }
yy31:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\'':	goto yy226;
	default:	goto yy32;
	}
yy32:
	{ return QUOTE_SINGLE; }
yy33:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy218;
	case '.':	goto yy219;
	default:	goto yy3;
	}
yy34:
	++YYCURSOR;
	{ return COLON; }
yy36:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy213;
	default:	goto yy37;
	}
yy37:
	{ return AMPERSAND; }
yy38:
	++YYCURSOR;
	{ return SLASH; }
yy40:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy136;
	case '\r':	goto yy138;
	case ' ':	goto yy141;
	case '!':	goto yy201;
	case '"':	goto yy191;
	case '#':	goto yy171;
	case '$':	goto yy169;
	case '%':	goto yy167;
	case '&':	goto yy155;
	case '\'':	goto yy189;
	case '(':	goto yy183;
	case ')':	goto yy181;
	case '*':	goto yy147;
	case '+':	goto yy165;
	case ',':	goto yy197;
	case '-':	goto yy163;
	case '.':	goto yy203;
	case '/':	goto yy151;
	case ':':	goto yy193;
	case ';':	goto yy195;
	case '<':	goto yy159;
	case '=':	goto yy161;
	case '>':	goto yy157;
	case '?':	goto yy199;
	case '@':	goto yy153;
	case '[':	goto yy175;
	case '\\':	goto yy139;
	case ']':	goto yy173;
	case '^':	goto yy149;
	case '_':	goto yy145;
	case '`':	goto yy187;
	case '{':	goto yy179;
	case '|':	goto yy143;
	case '}':	goto yy177;
	case '~':	goto yy185;
	default:	goto yy41;
	}
yy41:
	{ return TEXT_BACKSLASH; }
yy42:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy134;
	default:	goto yy43;
	}
yy43:
	{ return MATH_DOLLAR_SINGLE; }
yy44:
	++YYCURSOR;
	{ return SUPERSCRIPT; }
yy46:
	++YYCURSOR;
	{ return INDENT_TAB; }
yy48:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':	goto yy121;
	case '\n':	goto yy55;
	case '\r':	goto yy133;
	case ' ':
	case 0xA0:	goto yy123;
	default:	goto yy3;
	}
yy49:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':	goto yy121;
	case ' ':
	case 0xA0:	goto yy123;
	default:	goto yy3;
	}
yy50:
	YYCTXMARKER = YYCURSOR + 1;
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xA0:	goto yy82;
	case '#':	goto yy80;
	default:	goto yy51;
	}
yy51:
	{ return TEXT_HASH; }
yy52:
	++YYCURSOR;
	{ return TEXT_PERCENT; }
yy54:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy71;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy73;
	default:	goto yy3;
	}
yy55:
	++YYCURSOR;
yy56:
	{ return TEXT_NL; }
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy55;
	default:	goto yy56;
	}
yy58:
	++YYCURSOR;
	{ return STAR; }
yy60:
	++YYCURSOR;
	{ return UL; }
yy62:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy70;
yy63:
	{ return BACKTICK; }
yy64:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy68;
yy65:
	{ return PIPE; }
yy66:
	yych = *++YYCURSOR;
	goto yy3;
yy67:
	++YYCURSOR;
	yych = *YYCURSOR;
yy68:
	switch (yych) {
	case '|':	goto yy67;
	default:	goto yy65;
	}
yy69:
	++YYCURSOR;
	yych = *YYCURSOR;
yy70:
	switch (yych) {
	case '`':	goto yy69;
	default:	goto yy63;
	}
yy71:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy78;
	case '\n':	goto yy75;
	case '\r':	goto yy77;
	default:	goto yy72;
	}
yy72:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy7;
	case 2: 	goto yy11;
	case 3: 	goto yy13;
	case 4: 	goto yy15;
	case 5: 	goto yy3;
	case 6: 	goto yy37;
	case 7: 	goto yy51;
	case 8: 	goto yy130;
	default:	goto yy263;
	}
yy73:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy71;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy73;
	default:	goto yy72;
	}
yy75:
	++YYCURSOR;
yy76:
	YYCURSOR = YYCTXMARKER;
	{ return TEXT_NUMBER_POSS_LIST; }
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy75;
	default:	goto yy76;
	}
yy78:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy78;
	default:	goto yy76;
	}
yy80:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xA0:	goto yy88;
	case '#':	goto yy93;
	default:	goto yy72;
	}
yy81:
	++YYCURSOR;
	yych = *YYCURSOR;
yy82:
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy81;
	case '\n':	goto yy84;
	case '\r':	goto yy86;
	default:	goto yy83;
	}
yy83:
	{ return HASH1; }
yy84:
	++YYCURSOR;
yy85:
	YYCURSOR = YYCTXMARKER;
	{ return HASH1; }
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy84;
	default:	goto yy85;
	}
yy87:
	++YYCURSOR;
	yych = *YYCURSOR;
yy88:
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy87;
	case '\n':	goto yy90;
	case '\r':	goto yy92;
	default:	goto yy89;
	}
yy89:
	{ return HASH2; }
yy90:
	++YYCURSOR;
yy91:
	YYCURSOR = YYCTXMARKER;
	{ return HASH2; }
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy90;
	default:	goto yy91;
	}
yy93:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xA0:	goto yy96;
	case '#':	goto yy94;
	default:	goto yy72;
	}
yy94:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xA0:	goto yy102;
	case '#':	goto yy107;
	default:	goto yy72;
	}
yy95:
	++YYCURSOR;
	yych = *YYCURSOR;
yy96:
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy95;
	case '\n':	goto yy98;
	case '\r':	goto yy100;
	default:	goto yy97;
	}
yy97:
	{ return HASH3; }
yy98:
	++YYCURSOR;
yy99:
	YYCURSOR = YYCTXMARKER;
	{ return HASH3; }
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy98;
	default:	goto yy99;
	}
yy101:
	++YYCURSOR;
	yych = *YYCURSOR;
yy102:
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy101;
	case '\n':	goto yy104;
	case '\r':	goto yy106;
	default:	goto yy103;
	}
yy103:
	{ return HASH4; }
yy104:
	++YYCURSOR;
yy105:
	YYCURSOR = YYCTXMARKER;
	{ return HASH4; }
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy104;
	default:	goto yy105;
	}
yy107:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xA0:	goto yy110;
	case '#':	goto yy108;
	default:	goto yy72;
	}
yy108:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xA0:	goto yy116;
	default:	goto yy72;
	}
yy109:
	++YYCURSOR;
	yych = *YYCURSOR;
yy110:
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy109;
	case '\n':	goto yy112;
	case '\r':	goto yy114;
	default:	goto yy111;
	}
yy111:
	{ return HASH5; }
yy112:
	++YYCURSOR;
yy113:
	YYCURSOR = YYCTXMARKER;
	{ return HASH5; }
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy112;
	default:	goto yy113;
	}
yy115:
	++YYCURSOR;
	yych = *YYCURSOR;
yy116:
	switch (yych) {
	case '\t':
	case ' ':
	case 0xA0:	goto yy115;
	case '\n':	goto yy118;
	case '\r':	goto yy120;
	default:	goto yy117;
	}
yy117:
	{ return HASH6; }
yy118:
	++YYCURSOR;
yy119:
	YYCURSOR = YYCTXMARKER;
	{ return HASH6; }
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy118;
	default:	goto yy119;
	}
yy121:
	++YYCURSOR;
	YYCURSOR = YYCTXMARKER;
	{ return NON_INDENT_SPACE; }
yy123:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy126;
	case '\r':	goto yy128;
	case ' ':
	case 0xA0:	goto yy125;
	default:	goto yy124;
	}
yy124:
	{ return NON_INDENT_SPACE; }
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy126;
	case '\r':	goto yy128;
	case ' ':
	case 0xA0:	goto yy129;
	default:	goto yy124;
	}
yy126:
	++YYCURSOR;
yy127:
	{ return TEXT_LINEBREAK; }
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy126;
	default:	goto yy127;
	}
yy129:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy126;
	case '\r':	goto yy128;
	case ' ':
	case 0xA0:	goto yy131;
	default:	goto yy130;
	}
yy130:
	{ return INDENT_SPACE; }
yy131:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy126;
	case '\r':	goto yy128;
	case ' ':
	case 0xA0:	goto yy131;
	default:	goto yy72;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy55;
	default:	goto yy56;
	}
yy134:
	++YYCURSOR;
	{ return MATH_DOLLAR_DOUBLE; }
yy136:
	++YYCURSOR;
yy137:
	{ return TEXT_LINEBREAK; }
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy136;
	default:	goto yy137;
	}
yy139:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '(':	goto yy205;
	case ')':	goto yy207;
	case '[':	goto yy209;
	case ']':	goto yy211;
	default:	goto yy140;
	}
yy140:
	{ return ESCAPED_CHARACTER; }
yy141:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy143:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy145:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy147:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy149:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy151:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy153:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy155:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy157:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy159:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy161:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy163:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy165:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy167:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy169:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy171:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy173:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy175:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy177:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy179:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy181:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy183:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy185:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy187:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy189:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy191:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy193:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy195:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy197:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy199:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy201:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy203:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy205:
	++YYCURSOR;
	{ return MATH_PAREN_OPEN; }
yy207:
	++YYCURSOR;
	{ return MATH_PAREN_CLOSE; }
yy209:
	++YYCURSOR;
	{ return MATH_BRACKET_OPEN; }
yy211:
	++YYCURSOR;
	{ return MATH_BRACKET_CLOSE; }
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy214;
	default:	goto yy72;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy215;
	default:	goto yy72;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case ';':	goto yy216;
	default:	goto yy72;
	}
yy216:
	++YYCURSOR;
	{ return AMPERSAND_LONG; }
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy222;
	default:	goto yy72;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy220;
	default:	goto yy72;
	}
yy220:
	++YYCURSOR;
	{ return ELLIPSIS; }
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy223;
	default:	goto yy72;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy224;
	default:	goto yy72;
	}
yy224:
	++YYCURSOR;
	{ return ELLIPSIS; }
yy226:
	++YYCURSOR;
	{ return QUOTE_RIGHT_ALT; }
yy228:
	++YYCURSOR;
	{ return BRACE_DOUBLE_RIGHT; }
yy230:
	++YYCURSOR;
	{ return BRACKET_IMAGE_LEFT; }
yy232:
	++YYCURSOR;
	{ return BRACKET_VARIABLE_LEFT; }
yy234:
	++YYCURSOR;
	{ return BRACKET_GLOSSARY_LEFT; }
yy236:
	++YYCURSOR;
	{ return BRACKET_FOOTNOTE_LEFT; }
yy238:
	++YYCURSOR;
	{ return BRACKET_CITATION_LEFT; }
yy240:
	++YYCURSOR;
	{ return BRACKET_ABBREVIATION_LEFT; }
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy243;
	default:	goto yy72;
	}
yy243:
	++YYCURSOR;
	{ return CRITIC_HI_CLOSE; }
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy248;
	default:	goto yy72;
	}
yy246:
	++YYCURSOR;
	{ return CRITIC_SUB_DIV; }
yy248:
	++YYCURSOR;
	{ return CRITIC_SUB_CLOSE; }
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy251;
	default:	goto yy72;
	}
yy251:
	++YYCURSOR;
	{ return CRITIC_COM_CLOSE; }
yy253:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy257;
	case '}':	goto yy255;
	default:	goto yy254;
	}
yy254:
	{ return DASH_N; }
yy255:
	++YYCURSOR;
	{ return CRITIC_DEL_CLOSE; }
yy257:
	++YYCURSOR;
	{ return DASH_M; }
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy260;
	default:	goto yy72;
	}
yy260:
	++YYCURSOR;
	{ return CRITIC_ADD_CLOSE; }
yy262:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':	goto yy279;
	default:	goto yy263;
	}
yy263:
	{ return BRACE_DOUBLE_LEFT; }
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy277;
	default:	goto yy72;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case '~':	goto yy275;
	default:	goto yy72;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy273;
	default:	goto yy72;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy271;
	default:	goto yy72;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':	goto yy269;
	default:	goto yy72;
	}
yy269:
	++YYCURSOR;
	{ return CRITIC_ADD_OPEN; }
yy271:
	++YYCURSOR;
	{ return CRITIC_DEL_OPEN; }
yy273:
	++YYCURSOR;
	{ return CRITIC_COM_OPEN; }
yy275:
	++YYCURSOR;
	{ return CRITIC_SUB_OPEN; }
yy277:
	++YYCURSOR;
	{ return CRITIC_HI_OPEN; }
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy280;
	default:	goto yy72;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy281;
	default:	goto yy72;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy282;
	default:	goto yy72;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy283;
	default:	goto yy72;
	}
yy283:
	++YYCURSOR;
	{ return TOC; }
yy285:
	++YYCURSOR;
	{ return TEXT_PLAIN; }
}

}
