/* Generated by re2c 0.14.3 on Wed Mar 29 18:33:51 2017 */
/**

	MultiMarkdown 6 -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file lexer.re

	@brief Description of the regular expressions used to define tokens, 
	used by re2c to create a lexer/tokenizer.


	@author	Fletcher T. Penney
	@bug	

**/

/*

	Copyright © 2016 - 2017 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..
	
	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:
	
		https://github.com/fletcher/MultiMarkdown-4/
	
	MMD 4 is released under both the MIT License and GPL.
	
	
	CuTest is released under the zlib/libpng license. See CuTest.c for the text
	of the license.
	
	
	## The MIT License ##
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

*/

#include "lexer.h"
#include "libMultiMarkdown.h"
#include "parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int scan(Scanner * s, const char * stop) {

	scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;

	
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\v':
	case '\f':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ',':
	case ';':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case 0x7F:	goto yy67;
	case '\t':	goto yy47;
	case '\n':	goto yy56;
	case '\r':	goto yy58;
	case ' ':	goto yy49;
	case '!':	goto yy20;
	case '"':	goto yy30;
	case '#':	goto yy51;
	case '$':	goto yy43;
	case '%':	goto yy53;
	case '&':	goto yy37;
	case '\'':	goto yy32;
	case '(':	goto yy22;
	case ')':	goto yy24;
	case '*':	goto yy59;
	case '+':	goto yy6;
	case '-':	goto yy8;
	case '.':	goto yy34;
	case '/':	goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy55;
	case ':':	goto yy35;
	case '<':	goto yy10;
	case '=':	goto yy14;
	case '>':	goto yy26;
	case '[':	goto yy16;
	case '\\':	goto yy41;
	case ']':	goto yy18;
	case '^':	goto yy45;
	case '_':	goto yy61;
	case '`':	goto yy63;
	case '{':	goto yy4;
	case '|':	goto yy65;
	case '}':	goto yy28;
	case '~':	goto yy12;
	case 0xC2:	goto yy50;
	case 0xC3:	goto yy3;
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy68;
	case 0xE0:	goto yy69;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy70;
	case 0xF0:	goto yy71;
	case 0xF1:
	case 0xF2:
	case 0xF3:	goto yy72;
	case 0xF4:	goto yy73;
	default:	goto yy2;
	}
yy2:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy7;
	case 2: 	goto yy11;
	case 3: 	goto yy13;
	case 4: 	goto yy15;
	case 5: 	goto yy21;
	case 6: 	goto yy38;
	case 7: 	goto yy52;
	case 8: 	goto yy82;
	case 9: 	goto yy90;
	case 10: 	goto yy97;
	case 11: 	goto yy106;
	case 12: 	goto yy113;
	case 13: 	goto yy122;
	case 14: 	goto yy129;
	case 15: 	goto yy136;
	case 16: 	goto yy146;
	default:	goto yy281;
	}
yy3:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy67;
	case 0x83:	goto yy303;
	default:	goto yy2;
	}
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy286;
	case '-':	goto yy285;
	case '=':	goto yy282;
	case '>':	goto yy284;
	case '{':	goto yy280;
	case '~':	goto yy283;
	default:	goto yy5;
	}
yy5:
	{ return TEXT_BRACE_LEFT; }
yy6:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy277;
	default:	goto yy7;
	}
yy7:
	{ return PLUS; }
yy8:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy271;
	default:	goto yy9;
	}
yy9:
	{ return DASH_N; }
yy10:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '<':	goto yy268;
	default:	goto yy11;
	}
yy11:
	{ return ANGLE_LEFT; }
yy12:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '>':	goto yy264;
	case '~':	goto yy263;
	default:	goto yy13;
	}
yy13:
	{ return SUBSCRIPT; }
yy14:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy260;
	default:	goto yy15;
	}
yy15:
	{ return EQUAL; }
yy16:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '#':	goto yy256;
	case '%':	goto yy250;
	case '>':	goto yy258;
	case '?':	goto yy252;
	case '^':	goto yy254;
	default:	goto yy17;
	}
yy17:
	{ return BRACKET_LEFT; }
yy18:
	++YYCURSOR;
	{ return BRACKET_RIGHT; }
yy20:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '[':	goto yy248;
	default:	goto yy21;
	}
yy21:
	{ goto scan; }
yy22:
	++YYCURSOR;
	{ return PAREN_LEFT; }
yy24:
	++YYCURSOR;
	{ return PAREN_RIGHT; }
yy26:
	++YYCURSOR;
	{ return ANGLE_RIGHT; }
yy28:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '}':	goto yy246;
	default:	goto yy29;
	}
yy29:
	{ return TEXT_BRACE_RIGHT; }
yy30:
	++YYCURSOR;
	{ return QUOTE_DOUBLE; }
yy32:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\'':	goto yy244;
	default:	goto yy33;
	}
yy33:
	{ return QUOTE_SINGLE; }
yy34:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy236;
	case '.':	goto yy237;
	default:	goto yy21;
	}
yy35:
	++YYCURSOR;
	{ return COLON; }
yy37:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'A':
	case 'a':	goto yy231;
	default:	goto yy38;
	}
yy38:
	{ return AMPERSAND; }
yy39:
	++YYCURSOR;
	{ return SLASH; }
yy41:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy154;
	case '\r':	goto yy156;
	case ' ':	goto yy159;
	case '!':	goto yy219;
	case '"':	goto yy209;
	case '#':	goto yy189;
	case '$':	goto yy187;
	case '%':	goto yy185;
	case '&':	goto yy173;
	case '\'':	goto yy207;
	case '(':	goto yy201;
	case ')':	goto yy199;
	case '*':	goto yy165;
	case '+':	goto yy183;
	case ',':	goto yy215;
	case '-':	goto yy181;
	case '.':	goto yy221;
	case '/':	goto yy169;
	case ':':	goto yy211;
	case ';':	goto yy213;
	case '<':	goto yy177;
	case '=':	goto yy179;
	case '>':	goto yy175;
	case '?':	goto yy217;
	case '@':	goto yy171;
	case '[':	goto yy193;
	case '\\':	goto yy157;
	case ']':	goto yy191;
	case '^':	goto yy167;
	case '_':	goto yy163;
	case '`':	goto yy205;
	case '{':	goto yy197;
	case '|':	goto yy161;
	case '}':	goto yy195;
	case '~':	goto yy203;
	default:	goto yy42;
	}
yy42:
	{ return TEXT_BACKSLASH; }
yy43:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy152;
	default:	goto yy44;
	}
yy44:
	{ return MATH_DOLLAR_SINGLE; }
yy45:
	++YYCURSOR;
	{ return SUPERSCRIPT; }
yy47:
	++YYCURSOR;
	{ return INDENT_TAB; }
yy49:
	YYCTXMARKER = YYCURSOR + 1;
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':	goto yy138;
	case '\n':	goto yy56;
	case '\r':	goto yy151;
	case ' ':	goto yy135;
	case 0xC2:	goto yy137;
	default:	goto yy21;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy67;
	case 0xA0:	goto yy134;
	default:	goto yy2;
	}
yy51:
	YYCTXMARKER = YYCURSOR + 1;
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy89;
	case '#':	goto yy87;
	default:	goto yy52;
	}
yy52:
	{ return TEXT_HASH; }
yy53:
	++YYCURSOR;
	{ return TEXT_PERCENT; }
yy55:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy78;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy79;
	default:	goto yy21;
	}
yy56:
	++YYCURSOR;
yy57:
	{ return TEXT_NL; }
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy56;
	default:	goto yy57;
	}
yy59:
	++YYCURSOR;
	{ return STAR; }
yy61:
	++YYCURSOR;
	{ return UL; }
yy63:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy77;
yy64:
	{ return BACKTICK; }
yy65:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy75;
yy66:
	{ return PIPE; }
yy67:
	yych = *++YYCURSOR;
	goto yy21;
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy67;
	default:	goto yy2;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy68;
	default:	goto yy2;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy68;
	default:	goto yy2;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy70;
	default:	goto yy2;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy70;
	default:	goto yy2;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:	goto yy70;
	default:	goto yy2;
	}
yy74:
	++YYCURSOR;
	yych = *YYCURSOR;
yy75:
	switch (yych) {
	case '|':	goto yy74;
	default:	goto yy66;
	}
yy76:
	++YYCURSOR;
	yych = *YYCURSOR;
yy77:
	switch (yych) {
	case '`':	goto yy76;
	default:	goto yy64;
	}
yy78:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy84;
	case '\n':	goto yy81;
	case '\r':	goto yy83;
	case 0xC2:	goto yy86;
	default:	goto yy2;
	}
yy79:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy78;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy79;
	default:	goto yy2;
	}
yy81:
	++YYCURSOR;
yy82:
	YYCURSOR = YYCTXMARKER;
	{ return TEXT_NUMBER_POSS_LIST; }
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy81;
	default:	goto yy82;
	}
yy84:
	yyaccept = 8;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy84;
	case 0xC2:	goto yy86;
	default:	goto yy82;
	}
yy86:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy84;
	default:	goto yy2;
	}
yy87:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy96;
	case '#':	goto yy102;
	default:	goto yy2;
	}
yy88:
	yyaccept = 9;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy89:
	switch (yych) {
	case '\t':
	case ' ':	goto yy88;
	case '\n':	goto yy92;
	case '\r':	goto yy94;
	case 0xC2:	goto yy91;
	default:	goto yy90;
	}
yy90:
	{ return HASH1; }
yy91:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy88;
	default:	goto yy2;
	}
yy92:
	++YYCURSOR;
yy93:
	YYCURSOR = YYCTXMARKER;
	{ return HASH1; }
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy92;
	default:	goto yy93;
	}
yy95:
	yyaccept = 10;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy96:
	switch (yych) {
	case '\t':
	case ' ':	goto yy95;
	case '\n':	goto yy99;
	case '\r':	goto yy101;
	case 0xC2:	goto yy98;
	default:	goto yy97;
	}
yy97:
	{ return HASH2; }
yy98:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy95;
	default:	goto yy2;
	}
yy99:
	++YYCURSOR;
yy100:
	YYCURSOR = YYCTXMARKER;
	{ return HASH2; }
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy99;
	default:	goto yy100;
	}
yy102:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy105;
	case '#':	goto yy103;
	default:	goto yy2;
	}
yy103:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy112;
	case '#':	goto yy118;
	default:	goto yy2;
	}
yy104:
	yyaccept = 11;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy105:
	switch (yych) {
	case '\t':
	case ' ':	goto yy104;
	case '\n':	goto yy108;
	case '\r':	goto yy110;
	case 0xC2:	goto yy107;
	default:	goto yy106;
	}
yy106:
	{ return HASH3; }
yy107:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy104;
	default:	goto yy2;
	}
yy108:
	++YYCURSOR;
yy109:
	YYCURSOR = YYCTXMARKER;
	{ return HASH3; }
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy108;
	default:	goto yy109;
	}
yy111:
	yyaccept = 12;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy112:
	switch (yych) {
	case '\t':
	case ' ':	goto yy111;
	case '\n':	goto yy115;
	case '\r':	goto yy117;
	case 0xC2:	goto yy114;
	default:	goto yy113;
	}
yy113:
	{ return HASH4; }
yy114:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy111;
	default:	goto yy2;
	}
yy115:
	++YYCURSOR;
yy116:
	YYCURSOR = YYCTXMARKER;
	{ return HASH4; }
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy115;
	default:	goto yy116;
	}
yy118:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy121;
	case '#':	goto yy119;
	default:	goto yy2;
	}
yy119:
	YYCTXMARKER = YYCURSOR + 1;
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy128;
	default:	goto yy2;
	}
yy120:
	yyaccept = 13;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy121:
	switch (yych) {
	case '\t':
	case ' ':	goto yy120;
	case '\n':	goto yy124;
	case '\r':	goto yy126;
	case 0xC2:	goto yy123;
	default:	goto yy122;
	}
yy122:
	{ return HASH5; }
yy123:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy120;
	default:	goto yy2;
	}
yy124:
	++YYCURSOR;
yy125:
	YYCURSOR = YYCTXMARKER;
	{ return HASH5; }
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy124;
	default:	goto yy125;
	}
yy127:
	yyaccept = 14;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy128:
	switch (yych) {
	case '\t':
	case ' ':	goto yy127;
	case '\n':	goto yy131;
	case '\r':	goto yy133;
	case 0xC2:	goto yy130;
	default:	goto yy129;
	}
yy129:
	{ return HASH6; }
yy130:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy127;
	default:	goto yy2;
	}
yy131:
	++YYCURSOR;
yy132:
	YYCURSOR = YYCTXMARKER;
	{ return HASH6; }
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy131;
	default:	goto yy132;
	}
yy134:
	YYCTXMARKER = YYCURSOR + 1;
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':	goto yy138;
	case ' ':	goto yy135;
	case 0xC2:	goto yy137;
	default:	goto yy21;
	}
yy135:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy142;
	case '\r':	goto yy144;
	case ' ':	goto yy140;
	case 0xC2:	goto yy141;
	default:	goto yy136;
	}
yy136:
	{ return NON_INDENT_SPACE; }
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy135;
	default:	goto yy2;
	}
yy138:
	++YYCURSOR;
	YYCURSOR = YYCTXMARKER;
	{ return NON_INDENT_SPACE; }
yy140:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy142;
	case '\r':	goto yy144;
	case ' ':	goto yy145;
	case 0xC2:	goto yy147;
	default:	goto yy136;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy140;
	default:	goto yy2;
	}
yy142:
	++YYCURSOR;
yy143:
	{ return TEXT_LINEBREAK; }
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy142;
	default:	goto yy143;
	}
yy145:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy142;
	case '\r':	goto yy144;
	case ' ':	goto yy148;
	case 0xC2:	goto yy150;
	default:	goto yy146;
	}
yy146:
	{ return INDENT_SPACE; }
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy145;
	default:	goto yy2;
	}
yy148:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy142;
	case '\r':	goto yy144;
	case ' ':	goto yy148;
	case 0xC2:	goto yy150;
	default:	goto yy2;
	}
yy150:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy148;
	default:	goto yy2;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy56;
	default:	goto yy57;
	}
yy152:
	++YYCURSOR;
	{ return MATH_DOLLAR_DOUBLE; }
yy154:
	++YYCURSOR;
yy155:
	{ return TEXT_LINEBREAK; }
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy154;
	default:	goto yy155;
	}
yy157:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '(':	goto yy223;
	case ')':	goto yy225;
	case '[':	goto yy227;
	case ']':	goto yy229;
	default:	goto yy158;
	}
yy158:
	{ return ESCAPED_CHARACTER; }
yy159:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy161:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy163:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy165:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy167:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy169:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy171:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy173:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy175:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy177:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy179:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy181:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy183:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy185:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy187:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy189:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy191:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy193:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy195:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy197:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy199:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy201:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy203:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy205:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy207:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy209:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy211:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy213:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy215:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy217:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy219:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy221:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy223:
	++YYCURSOR;
	{ return MATH_PAREN_OPEN; }
yy225:
	++YYCURSOR;
	{ return MATH_PAREN_CLOSE; }
yy227:
	++YYCURSOR;
	{ return MATH_BRACKET_OPEN; }
yy229:
	++YYCURSOR;
	{ return MATH_BRACKET_CLOSE; }
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy232;
	default:	goto yy2;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy233;
	default:	goto yy2;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case ';':	goto yy234;
	default:	goto yy2;
	}
yy234:
	++YYCURSOR;
	{ return AMPERSAND_LONG; }
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy240;
	default:	goto yy2;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy238;
	default:	goto yy2;
	}
yy238:
	++YYCURSOR;
	{ return ELLIPSIS; }
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy241;
	default:	goto yy2;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy242;
	default:	goto yy2;
	}
yy242:
	++YYCURSOR;
	{ return ELLIPSIS; }
yy244:
	++YYCURSOR;
	{ return QUOTE_RIGHT_ALT; }
yy246:
	++YYCURSOR;
	{ return BRACE_DOUBLE_RIGHT; }
yy248:
	++YYCURSOR;
	{ return BRACKET_IMAGE_LEFT; }
yy250:
	++YYCURSOR;
	{ return BRACKET_VARIABLE_LEFT; }
yy252:
	++YYCURSOR;
	{ return BRACKET_GLOSSARY_LEFT; }
yy254:
	++YYCURSOR;
	{ return BRACKET_FOOTNOTE_LEFT; }
yy256:
	++YYCURSOR;
	{ return BRACKET_CITATION_LEFT; }
yy258:
	++YYCURSOR;
	{ return BRACKET_ABBREVIATION_LEFT; }
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy261;
	default:	goto yy2;
	}
yy261:
	++YYCURSOR;
	{ return CRITIC_HI_CLOSE; }
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy266;
	default:	goto yy2;
	}
yy264:
	++YYCURSOR;
	{ return CRITIC_SUB_DIV; }
yy266:
	++YYCURSOR;
	{ return CRITIC_SUB_CLOSE; }
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy269;
	default:	goto yy2;
	}
yy269:
	++YYCURSOR;
	{ return CRITIC_COM_CLOSE; }
yy271:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy275;
	case '}':	goto yy273;
	default:	goto yy272;
	}
yy272:
	{ return DASH_N; }
yy273:
	++YYCURSOR;
	{ return CRITIC_DEL_CLOSE; }
yy275:
	++YYCURSOR;
	{ return DASH_M; }
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy278;
	default:	goto yy2;
	}
yy278:
	++YYCURSOR;
	{ return CRITIC_ADD_CLOSE; }
yy280:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':	goto yy297;
	default:	goto yy281;
	}
yy281:
	{ return BRACE_DOUBLE_LEFT; }
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy295;
	default:	goto yy2;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case '~':	goto yy293;
	default:	goto yy2;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy291;
	default:	goto yy2;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy289;
	default:	goto yy2;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':	goto yy287;
	default:	goto yy2;
	}
yy287:
	++YYCURSOR;
	{ return CRITIC_ADD_OPEN; }
yy289:
	++YYCURSOR;
	{ return CRITIC_DEL_OPEN; }
yy291:
	++YYCURSOR;
	{ return CRITIC_COM_OPEN; }
yy293:
	++YYCURSOR;
	{ return CRITIC_SUB_OPEN; }
yy295:
	++YYCURSOR;
	{ return CRITIC_HI_OPEN; }
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy298;
	default:	goto yy2;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy299;
	default:	goto yy2;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy300;
	default:	goto yy2;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy301;
	default:	goto yy2;
	}
yy301:
	++YYCURSOR;
	{ return TOC; }
yy303:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0xC2:	goto yy304;
	default:	goto yy21;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy305;
	default:	goto yy2;
	}
yy305:
	++YYCURSOR;
	{ return TEXT_PLAIN; }
}

}
