/* Generated by re2c 0.15.3 on Sun Jul 23 08:32:21 2017 */
/**

	MultiMarkdown 6 -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file lexer.re

	@brief Description of the regular expressions used to define tokens, 
	used by re2c to create a lexer/tokenizer.


	@author	Fletcher T. Penney
	@bug	

**/

/*

	Copyright © 2016 - 2017 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..
	
	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:
	
		https://github.com/fletcher/MultiMarkdown-4/
	
	MMD 4 is released under both the MIT License and GPL.
	
	
	CuTest is released under the zlib/libpng license. See CuTest.c for the text
	of the license.
	
	
	## The MIT License ##
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

*/

#include "lexer.h"
#include "libMultiMarkdown.h"
#include "parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int scan(Scanner * s, const char * stop) {

	scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;

	
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\v':
	case '\f':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ',':
	case ';':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case 0x7F:	goto yy66;
	case '\t':	goto yy49;
	case '\n':	goto yy3;
	case '\r':	goto yy5;
	case ' ':	goto yy51;
	case '!':	goto yy22;
	case '"':	goto yy32;
	case '#':	goto yy53;
	case '$':	goto yy45;
	case '%':	goto yy55;
	case '&':	goto yy39;
	case '\'':	goto yy34;
	case '(':	goto yy24;
	case ')':	goto yy26;
	case '*':	goto yy58;
	case '+':	goto yy8;
	case '-':	goto yy10;
	case '.':	goto yy36;
	case '/':	goto yy41;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy57;
	case ':':	goto yy37;
	case '<':	goto yy12;
	case '=':	goto yy16;
	case '>':	goto yy28;
	case '[':	goto yy18;
	case '\\':	goto yy43;
	case ']':	goto yy20;
	case '^':	goto yy47;
	case '_':	goto yy60;
	case '`':	goto yy62;
	case '{':	goto yy6;
	case '|':	goto yy64;
	case '}':	goto yy30;
	case '~':	goto yy14;
	case 0xC2:	goto yy52;
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy67;
	case 0xE0:	goto yy68;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy69;
	case 0xF0:	goto yy70;
	case 0xF1:
	case 0xF2:
	case 0xF3:	goto yy71;
	case 0xF4:	goto yy72;
	default:	goto yy2;
	}
yy2:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy4;
	case 1: 	goto yy7;
	case 2: 	goto yy9;
	case 3: 	goto yy13;
	case 4: 	goto yy15;
	case 5: 	goto yy17;
	case 6: 	goto yy23;
	case 7: 	goto yy40;
	case 8: 	goto yy54;
	case 9: 	goto yy81;
	case 10: 	goto yy89;
	case 11: 	goto yy96;
	case 12: 	goto yy105;
	case 13: 	goto yy112;
	case 14: 	goto yy121;
	case 15: 	goto yy128;
	case 16: 	goto yy135;
	case 17: 	goto yy145;
	default:	goto yy303;
	}
yy3:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy324;
	default:	goto yy4;
	}
yy4:
	{ return TEXT_NL; }
yy5:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy3;
	case ' ':	goto yy324;
	default:	goto yy4;
	}
yy6:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy307;
	case '-':	goto yy306;
	case '=':	goto yy300;
	case '>':	goto yy305;
	case '{':	goto yy302;
	case '~':	goto yy304;
	default:	goto yy7;
	}
yy7:
	{ return TEXT_BRACE_LEFT; }
yy8:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '+':	goto yy297;
	default:	goto yy9;
	}
yy9:
	{ return PLUS; }
yy10:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy289;
	default:	goto yy11;
	}
yy11:
	{ return DASH_N; }
yy12:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '!':	goto yy282;
	case '<':	goto yy283;
	default:	goto yy13;
	}
yy13:
	{ return ANGLE_LEFT; }
yy14:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '>':	goto yy278;
	case '~':	goto yy277;
	default:	goto yy15;
	}
yy15:
	{ return SUBSCRIPT; }
yy16:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '=':	goto yy274;
	default:	goto yy17;
	}
yy17:
	{ return EQUAL; }
yy18:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '#':	goto yy270;
	case '%':	goto yy264;
	case '>':	goto yy272;
	case '?':	goto yy266;
	case '^':	goto yy268;
	default:	goto yy19;
	}
yy19:
	{ return BRACKET_LEFT; }
yy20:
	++YYCURSOR;
	{ return BRACKET_RIGHT; }
yy22:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '[':	goto yy262;
	default:	goto yy23;
	}
yy23:
	{ goto scan; }
yy24:
	++YYCURSOR;
	{ return PAREN_LEFT; }
yy26:
	++YYCURSOR;
	{ return PAREN_RIGHT; }
yy28:
	++YYCURSOR;
	{ return ANGLE_RIGHT; }
yy30:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '}':	goto yy260;
	default:	goto yy31;
	}
yy31:
	{ return TEXT_BRACE_RIGHT; }
yy32:
	++YYCURSOR;
	{ return QUOTE_DOUBLE; }
yy34:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\'':	goto yy258;
	default:	goto yy35;
	}
yy35:
	{ return QUOTE_SINGLE; }
yy36:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case ' ':	goto yy250;
	case '.':	goto yy251;
	default:	goto yy23;
	}
yy37:
	++YYCURSOR;
	{ return COLON; }
yy39:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '#':	goto yy234;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy231;
	case 'A':
	case 'a':	goto yy233;
	default:	goto yy40;
	}
yy40:
	{ return AMPERSAND; }
yy41:
	++YYCURSOR;
	{ return SLASH; }
yy43:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '\n':	goto yy154;
	case '\r':	goto yy156;
	case ' ':	goto yy159;
	case '!':	goto yy219;
	case '"':	goto yy209;
	case '#':	goto yy189;
	case '$':	goto yy187;
	case '%':	goto yy185;
	case '&':	goto yy173;
	case '\'':	goto yy207;
	case '(':	goto yy201;
	case ')':	goto yy199;
	case '*':	goto yy165;
	case '+':	goto yy183;
	case ',':	goto yy215;
	case '-':	goto yy181;
	case '.':	goto yy221;
	case '/':	goto yy169;
	case ':':	goto yy211;
	case ';':	goto yy213;
	case '<':	goto yy177;
	case '=':	goto yy179;
	case '>':	goto yy175;
	case '?':	goto yy217;
	case '@':	goto yy171;
	case '[':	goto yy193;
	case '\\':	goto yy157;
	case ']':	goto yy191;
	case '^':	goto yy167;
	case '_':	goto yy163;
	case '`':	goto yy205;
	case '{':	goto yy197;
	case '|':	goto yy161;
	case '}':	goto yy195;
	case '~':	goto yy203;
	default:	goto yy44;
	}
yy44:
	{ return TEXT_BACKSLASH; }
yy45:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '$':	goto yy152;
	default:	goto yy46;
	}
yy46:
	{ return MATH_DOLLAR_SINGLE; }
yy47:
	++YYCURSOR;
	{ return SUPERSCRIPT; }
yy49:
	++YYCURSOR;
	{ return INDENT_TAB; }
yy51:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':	goto yy137;
	case '\n':	goto yy150;
	case '\r':	goto yy151;
	case ' ':	goto yy134;
	case 0xC2:	goto yy136;
	default:	goto yy23;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy66;
	case 0xA0:	goto yy133;
	default:	goto yy2;
	}
yy53:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy88;
	case '#':	goto yy86;
	default:	goto yy54;
	}
yy54:
	{ return TEXT_HASH; }
yy55:
	++YYCURSOR;
	{ return TEXT_PERCENT; }
yy57:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy77;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy78;
	default:	goto yy23;
	}
yy58:
	++YYCURSOR;
	{ return STAR; }
yy60:
	++YYCURSOR;
	{ return UL; }
yy62:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy76;
yy63:
	{ return BACKTICK; }
yy64:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy74;
yy65:
	{ return PIPE; }
yy66:
	yych = *++YYCURSOR;
	goto yy23;
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy66;
	default:	goto yy2;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy67;
	default:	goto yy2;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy67;
	default:	goto yy2;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy69;
	default:	goto yy2;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy69;
	default:	goto yy2;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:	goto yy69;
	default:	goto yy2;
	}
yy73:
	++YYCURSOR;
	yych = *YYCURSOR;
yy74:
	switch (yych) {
	case '|':	goto yy73;
	default:	goto yy65;
	}
yy75:
	++YYCURSOR;
	yych = *YYCURSOR;
yy76:
	switch (yych) {
	case '`':	goto yy75;
	default:	goto yy63;
	}
yy77:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy83;
	case '\n':	goto yy80;
	case '\r':	goto yy82;
	case 0xC2:	goto yy85;
	default:	goto yy2;
	}
yy78:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy77;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy78;
	default:	goto yy2;
	}
yy80:
	++YYCURSOR;
yy81:
	YYCURSOR = YYCTXMARKER;
	{ return TEXT_NUMBER_POSS_LIST; }
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy80;
	default:	goto yy81;
	}
yy83:
	yyaccept = 9;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy83;
	case 0xC2:	goto yy85;
	default:	goto yy81;
	}
yy85:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy83;
	default:	goto yy2;
	}
yy86:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy95;
	case '#':	goto yy101;
	default:	goto yy2;
	}
yy87:
	yyaccept = 10;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy88:
	switch (yych) {
	case '\t':
	case ' ':	goto yy87;
	case '\n':	goto yy91;
	case '\r':	goto yy93;
	case 0xC2:	goto yy90;
	default:	goto yy89;
	}
yy89:
	{ return HASH1; }
yy90:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy87;
	default:	goto yy2;
	}
yy91:
	++YYCURSOR;
yy92:
	YYCURSOR = YYCTXMARKER;
	{ return HASH1; }
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy91;
	default:	goto yy92;
	}
yy94:
	yyaccept = 11;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy95:
	switch (yych) {
	case '\t':
	case ' ':	goto yy94;
	case '\n':	goto yy98;
	case '\r':	goto yy100;
	case 0xC2:	goto yy97;
	default:	goto yy96;
	}
yy96:
	{ return HASH2; }
yy97:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy94;
	default:	goto yy2;
	}
yy98:
	++YYCURSOR;
yy99:
	YYCURSOR = YYCTXMARKER;
	{ return HASH2; }
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy98;
	default:	goto yy99;
	}
yy101:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy104;
	case '#':	goto yy102;
	default:	goto yy2;
	}
yy102:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy111;
	case '#':	goto yy117;
	default:	goto yy2;
	}
yy103:
	yyaccept = 12;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy104:
	switch (yych) {
	case '\t':
	case ' ':	goto yy103;
	case '\n':	goto yy107;
	case '\r':	goto yy109;
	case 0xC2:	goto yy106;
	default:	goto yy105;
	}
yy105:
	{ return HASH3; }
yy106:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy103;
	default:	goto yy2;
	}
yy107:
	++YYCURSOR;
yy108:
	YYCURSOR = YYCTXMARKER;
	{ return HASH3; }
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy107;
	default:	goto yy108;
	}
yy110:
	yyaccept = 13;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy111:
	switch (yych) {
	case '\t':
	case ' ':	goto yy110;
	case '\n':	goto yy114;
	case '\r':	goto yy116;
	case 0xC2:	goto yy113;
	default:	goto yy112;
	}
yy112:
	{ return HASH4; }
yy113:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy110;
	default:	goto yy2;
	}
yy114:
	++YYCURSOR;
yy115:
	YYCURSOR = YYCTXMARKER;
	{ return HASH4; }
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy114;
	default:	goto yy115;
	}
yy117:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy120;
	case '#':	goto yy118;
	default:	goto yy2;
	}
yy118:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':
	case 0xC2:	goto yy127;
	default:	goto yy2;
	}
yy119:
	yyaccept = 14;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy120:
	switch (yych) {
	case '\t':
	case ' ':	goto yy119;
	case '\n':	goto yy123;
	case '\r':	goto yy125;
	case 0xC2:	goto yy122;
	default:	goto yy121;
	}
yy121:
	{ return HASH5; }
yy122:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy119;
	default:	goto yy2;
	}
yy123:
	++YYCURSOR;
yy124:
	YYCURSOR = YYCTXMARKER;
	{ return HASH5; }
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy123;
	default:	goto yy124;
	}
yy126:
	yyaccept = 15;
	YYMARKER = ++YYCURSOR;
	yych = *YYCURSOR;
yy127:
	switch (yych) {
	case '\t':
	case ' ':	goto yy126;
	case '\n':	goto yy130;
	case '\r':	goto yy132;
	case 0xC2:	goto yy129;
	default:	goto yy128;
	}
yy128:
	{ return HASH6; }
yy129:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy126;
	default:	goto yy2;
	}
yy130:
	++YYCURSOR;
yy131:
	YYCURSOR = YYCTXMARKER;
	{ return HASH6; }
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy130;
	default:	goto yy131;
	}
yy133:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case '\t':	goto yy137;
	case ' ':	goto yy134;
	case 0xC2:	goto yy136;
	default:	goto yy23;
	}
yy134:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy141;
	case '\r':	goto yy143;
	case ' ':	goto yy139;
	case 0xC2:	goto yy140;
	default:	goto yy135;
	}
yy135:
	{ return NON_INDENT_SPACE; }
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy134;
	default:	goto yy2;
	}
yy137:
	++YYCURSOR;
	YYCURSOR = YYCTXMARKER;
	{ return NON_INDENT_SPACE; }
yy139:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy141;
	case '\r':	goto yy143;
	case ' ':	goto yy144;
	case 0xC2:	goto yy146;
	default:	goto yy135;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy139;
	default:	goto yy2;
	}
yy141:
	++YYCURSOR;
yy142:
	{ return TEXT_LINEBREAK; }
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy141;
	default:	goto yy142;
	}
yy144:
	yyaccept = 17;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy141;
	case '\r':	goto yy143;
	case ' ':	goto yy147;
	case 0xC2:	goto yy149;
	default:	goto yy145;
	}
yy145:
	{ return INDENT_SPACE; }
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy144;
	default:	goto yy2;
	}
yy147:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy141;
	case '\r':	goto yy143;
	case ' ':	goto yy147;
	case 0xC2:	goto yy149;
	default:	goto yy2;
	}
yy149:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xA0:	goto yy147;
	default:	goto yy2;
	}
yy150:
	yych = *++YYCURSOR;
	goto yy4;
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy150;
	default:	goto yy4;
	}
yy152:
	++YYCURSOR;
	{ return MATH_DOLLAR_DOUBLE; }
yy154:
	++YYCURSOR;
yy155:
	{ return TEXT_LINEBREAK; }
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy154;
	default:	goto yy155;
	}
yy157:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '(':	goto yy223;
	case ')':	goto yy225;
	case '[':	goto yy227;
	case ']':	goto yy229;
	default:	goto yy158;
	}
yy158:
	{ return ESCAPED_CHARACTER; }
yy159:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy161:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy163:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy165:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy167:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy169:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy171:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy173:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy175:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy177:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy179:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy181:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy183:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy185:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy187:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy189:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy191:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy193:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy195:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy197:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy199:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy201:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy203:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy205:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy207:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy209:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy211:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy213:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy215:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy217:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy219:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy221:
	++YYCURSOR;
	{ return ESCAPED_CHARACTER; }
yy223:
	++YYCURSOR;
	{ return MATH_PAREN_OPEN; }
yy225:
	++YYCURSOR;
	{ return MATH_PAREN_CLOSE; }
yy227:
	++YYCURSOR;
	{ return MATH_BRACKET_OPEN; }
yy229:
	++YYCURSOR;
	{ return MATH_BRACKET_CLOSE; }
yy231:
	++YYCURSOR;
	yych = *YYCURSOR;
yy232:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy231;
	case ';':	goto yy245;
	default:	goto yy2;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':
	case 'm':	goto yy244;
	default:	goto yy232;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy236;
	case 'X':
	case 'x':	goto yy235;
	default:	goto yy2;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case ';':	goto yy2;
	default:	goto yy241;
	}
yy236:
	++YYCURSOR;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy236;
	case ';':	goto yy238;
	default:	goto yy2;
	}
yy238:
	++YYCURSOR;
	{ return HTML_ENTITY; }
yy240:
	++YYCURSOR;
	yych = *YYCURSOR;
yy241:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy240;
	case ';':	goto yy242;
	default:	goto yy2;
	}
yy242:
	++YYCURSOR;
	{ return HTML_ENTITY; }
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':
	case 'p':	goto yy247;
	default:	goto yy232;
	}
yy245:
	++YYCURSOR;
	{ return HTML_ENTITY; }
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case ';':	goto yy248;
	default:	goto yy232;
	}
yy248:
	++YYCURSOR;
	{ return AMPERSAND_LONG; }
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy254;
	default:	goto yy2;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy252;
	default:	goto yy2;
	}
yy252:
	++YYCURSOR;
	{ return ELLIPSIS; }
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy255;
	default:	goto yy2;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy256;
	default:	goto yy2;
	}
yy256:
	++YYCURSOR;
	{ return ELLIPSIS; }
yy258:
	++YYCURSOR;
	{ return QUOTE_RIGHT_ALT; }
yy260:
	++YYCURSOR;
	{ return BRACE_DOUBLE_RIGHT; }
yy262:
	++YYCURSOR;
	{ return BRACKET_IMAGE_LEFT; }
yy264:
	++YYCURSOR;
	{ return BRACKET_VARIABLE_LEFT; }
yy266:
	++YYCURSOR;
	{ return BRACKET_GLOSSARY_LEFT; }
yy268:
	++YYCURSOR;
	{ return BRACKET_FOOTNOTE_LEFT; }
yy270:
	++YYCURSOR;
	{ return BRACKET_CITATION_LEFT; }
yy272:
	++YYCURSOR;
	{ return BRACKET_ABBREVIATION_LEFT; }
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy275;
	default:	goto yy2;
	}
yy275:
	++YYCURSOR;
	{ return CRITIC_HI_CLOSE; }
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy280;
	default:	goto yy2;
	}
yy278:
	++YYCURSOR;
	{ return CRITIC_SUB_DIV; }
yy280:
	++YYCURSOR;
	{ return CRITIC_SUB_CLOSE; }
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy286;
	default:	goto yy2;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy284;
	default:	goto yy2;
	}
yy284:
	++YYCURSOR;
	{ return CRITIC_COM_CLOSE; }
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy287;
	default:	goto yy2;
	}
yy287:
	++YYCURSOR;
	{ return HTML_COMMENT_START; }
yy289:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy295;
	case '>':	goto yy293;
	case '}':	goto yy291;
	default:	goto yy290;
	}
yy290:
	{ return DASH_N; }
yy291:
	++YYCURSOR;
	{ return CRITIC_DEL_CLOSE; }
yy293:
	++YYCURSOR;
	{ return HTML_COMMENT_STOP; }
yy295:
	++YYCURSOR;
	{ return DASH_M; }
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy298;
	default:	goto yy2;
	}
yy298:
	++YYCURSOR;
	{ return CRITIC_ADD_CLOSE; }
yy300:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy322;
	default:	goto yy301;
	}
yy301:
	{ return RAW_FILTER_LEFT; }
yy302:
	yyaccept = 18;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':	goto yy316;
	default:	goto yy303;
	}
yy303:
	{ return BRACE_DOUBLE_LEFT; }
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case '~':	goto yy314;
	default:	goto yy2;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy312;
	default:	goto yy2;
	}
yy306:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy310;
	default:	goto yy2;
	}
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':	goto yy308;
	default:	goto yy2;
	}
yy308:
	++YYCURSOR;
	{ return CRITIC_ADD_OPEN; }
yy310:
	++YYCURSOR;
	{ return CRITIC_DEL_OPEN; }
yy312:
	++YYCURSOR;
	{ return CRITIC_COM_OPEN; }
yy314:
	++YYCURSOR;
	{ return CRITIC_SUB_OPEN; }
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy317;
	default:	goto yy2;
	}
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy318;
	default:	goto yy2;
	}
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy319;
	default:	goto yy2;
	}
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case '}':	goto yy320;
	default:	goto yy2;
	}
yy320:
	++YYCURSOR;
	{ return TOC; }
yy322:
	++YYCURSOR;
	{ return CRITIC_HI_OPEN; }
yy324:
	yych = *++YYCURSOR;
	YYCTXMARKER = YYCURSOR;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\v':
	case '\f':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy325;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy327;
	case 0xE0:	goto yy328;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy329;
	case 0xF0:	goto yy330;
	case 0xF1:
	case 0xF2:
	case 0xF3:	goto yy331;
	case 0xF4:	goto yy332;
	default:	goto yy2;
	}
yy325:
	++YYCURSOR;
	YYCURSOR = YYCTXMARKER;
	{ return TEXT_NL_SP; }
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy325;
	default:	goto yy2;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy327;
	default:	goto yy2;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy327;
	default:	goto yy2;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy329;
	default:	goto yy2;
	}
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy329;
	default:	goto yy2;
	}
yy332:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:	goto yy329;
	default:	goto yy2;
	}
}

}
