#define OPML_XML                         1
#define OPML_WSNL                        2
#define OPML_OPML_OPEN                   3
#define OPML_OPML_CLOSE                  4
#define OPML_HEAD_OPEN                   5
#define OPML_HEAD_CLOSE                  6
#define OPML_TITLE_OPEN                  7
#define OPML_TITLE_CLOSE                 8
#define OPML_BODY_OPEN                   9
#define OPML_BODY_CLOSE                 10
#define OPML_OUTLINE_OPEN               11
#define OPML_OUTLINE_CLOSE              12
#define OPML_OUTLINE_PREAMBLE           13
#define OPML_OUTLINE_METADATA           14
#define OPML_OUTLINE_SELF_CLOSE         15
