/* Generated by re2c 0.15.3 on Wed Sep  5 17:16:24 2018 */
/**

	MultiMarkdown -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file opml-lexer.c

	@brief Tokenize OPML file for parsing


	@author	Fletcher T. Penney
	@bug

**/

/*

	Copyright © 2016 - 2018 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..

	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:

		https://github.com/fletcher/MultiMarkdown-4/

	MMD 4 is released under both the MIT License and GPL.


	CuTest is released under the zlib/libpng license. See CuTest.c for the
	text of the license.

	uthash library:
		Copyright (c) 2005-2016, Troy D. Hanson

		Licensed under Revised BSD license

	miniz library:
		Copyright 2013-2014 RAD Game Tools and Valve Software
		Copyright 2010-2014 Rich Geldreich and Tenacious Software LLC

		Licensed under the MIT license

	argtable3 library:
		Copyright (C) 1998-2001,2003-2011,2013 Stewart Heitmann
		<sheitmann@users.sourceforge.net>
		All rights reserved.

		Licensed under the Revised BSD License


	## The MIT License ##

	Permission is hereby granted, free of charge, to any person obtaining
	a copy of this software and associated documentation files (the
	"Software"), to deal in the Software without restriction, including
	without limitation the rights to use, copy, modify, merge, publish,
	distribute, sublicense, and/or sell copies of the Software, and to
	permit persons to whom the Software is furnished to do so, subject to
	the following conditions:

	The above copyright notice and this permission notice shall be
	included in all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
	EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
	MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
	CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
	TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
	SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


	## Revised BSD License ##

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are
	met:
	    * Redistributions of source code must retain the above copyright
	      notice, this list of conditions and the following disclaimer.
	    * Redistributions in binary form must reproduce the above
	      copyright notice, this list of conditions and the following
	      disclaimer in the documentation and/or other materials provided
	      with the distribution.
	    * Neither the name of the <organization> nor the
	      names of its contributors may be used to endorse or promote
	      products derived from this software without specific prior
	      written permission.

	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
	"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
	LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
	A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT
	HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
	PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES LOSS OF USE, DATA, OR
	PROFITS OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
	LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
	NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


*/

#include <stdlib.h>

#include "opml-lexer.h"
#include "opml-parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int opml_scan(Scanner * s, const char * stop) {

scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;


	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
			case ' ':
				goto yy8;

			case '\n':
				goto yy4;

			case '\r':
				goto yy7;

			case '<':
				goto yy2;

			default:
				goto yy9;
		}

yy2:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '/':
				goto yy12;

			case '?':
				goto yy18;

			case 'B':
			case 'b':
				goto yy15;

			case 'H':
			case 'h':
				goto yy17;

			case 'O':
			case 'o':
				goto yy14;

			case 'T':
			case 't':
				goto yy16;

			default:
				goto yy3;
		}

yy3: {
			goto scan;
		}
yy4:
		++YYCURSOR;
		yych = *YYCURSOR;
yy5:

		switch (yych) {
			case '\t':
			case '\n':
			case ' ':
				goto yy4;

			case '\r':
				goto yy10;

			default:
				goto yy6;
		}

yy6: {
			return OPML_WSNL;
		}
yy7:
		yych = *++YYCURSOR;
		goto yy5;
yy8:
		yych = *++YYCURSOR;
		goto yy5;
yy9:
		yych = *++YYCURSOR;
		goto yy3;
yy10:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
			case '\n':
			case ' ':
				goto yy4;

			case '\r':
				goto yy10;

			default:
				goto yy6;
		}

yy12:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'B':
			case 'b':
				goto yy163;

			case 'H':
			case 'h':
				goto yy161;

			case 'O':
			case 'o':
				goto yy160;

			case 'T':
			case 't':
				goto yy162;

			default:
				goto yy13;
		}

yy13:
		YYCURSOR = YYMARKER;

		switch (yyaccept) {
			case 0:
				goto yy3;

			case 1:
				goto yy60;

			default:
				goto yy62;
		}

yy14:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'P':
			case 'p':
				goto yy44;

			case 'U':
			case 'u':
				goto yy45;

			default:
				goto yy13;
		}

yy15:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'O':
			case 'o':
				goto yy38;

			default:
				goto yy13;
		}

yy16:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'I':
			case 'i':
				goto yy31;

			default:
				goto yy13;
		}

yy17:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy25;

			default:
				goto yy13;
		}

yy18:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'X':
			case 'x':
				goto yy19;

			default:
				goto yy13;
		}

yy19:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy20;

			default:
				goto yy13;
		}

yy20:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy21;

			default:
				goto yy13;
		}

yy21:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '>':
				goto yy23;

			default:
				goto yy21;
		}

yy23:
		++YYCURSOR;
		{
			return OPML_XML;
		}
yy25:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'A':
			case 'a':
				goto yy26;

			default:
				goto yy13;
		}

yy26:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'D':
			case 'd':
				goto yy27;

			default:
				goto yy13;
		}

yy27:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '>':
				goto yy29;

			default:
				goto yy27;
		}

yy29:
		++YYCURSOR;
		{
			return OPML_HEAD_OPEN;
		}
yy31:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy32;

			default:
				goto yy13;
		}

yy32:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy33;

			default:
				goto yy13;
		}

yy33:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy34;

			default:
				goto yy13;
		}

yy34:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '>':
				goto yy36;

			default:
				goto yy34;
		}

yy36:
		++YYCURSOR;
		{
			return OPML_TITLE_OPEN;
		}
yy38:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'D':
			case 'd':
				goto yy39;

			default:
				goto yy13;
		}

yy39:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'Y':
			case 'y':
				goto yy40;

			default:
				goto yy13;
		}

yy40:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '>':
				goto yy42;

			default:
				goto yy40;
		}

yy42:
		++YYCURSOR;
		{
			return OPML_BODY_OPEN;
		}
yy44:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy155;

			default:
				goto yy13;
		}

yy45:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy46;

			default:
				goto yy13;
		}

yy46:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy47;

			default:
				goto yy13;
		}

yy47:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'I':
			case 'i':
				goto yy48;

			default:
				goto yy13;
		}

yy48:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'N':
			case 'n':
				goto yy49;

			default:
				goto yy13;
		}

yy49:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy50;

			default:
				goto yy13;
		}

yy50:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy50;

			case '\r':
				goto yy52;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			case 'T':
			case 't':
				goto yy54;

			default:
				goto yy55;
		}

yy52:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy50;

			case '\r':
				goto yy52;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			case 'T':
			case 't':
				goto yy54;

			default:
				goto yy55;
		}

yy54:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy63;

			default:
				goto yy56;
		}

yy55:
		++YYCURSOR;
		yych = *YYCURSOR;
yy56:

		switch (yych) {
			case 0x00:
				goto yy13;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy57:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '/':
				goto yy57;

			case '>':
				goto yy61;

			default:
				goto yy55;
		}

yy59:
		++YYCURSOR;
yy60: {
			return OPML_OUTLINE_OPEN;
		}
yy61:
		++YYCURSOR;
yy62: {
			return OPML_OUTLINE_SELF_CLOSE;
		}
yy63:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'X':
			case 'x':
				goto yy64;

			default:
				goto yy56;
		}

yy64:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy65;

			default:
				goto yy56;
		}

yy65:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy65;

			case '\r':
				goto yy67;

			case '/':
				goto yy57;

			case '=':
				goto yy69;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy67:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy65;

			case '\r':
				goto yy67;

			case '/':
				goto yy57;

			case '=':
				goto yy69;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy69:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy69;

			case '\r':
				goto yy71;

			case '"':
				goto yy73;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy71:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy69;

			case '\r':
				goto yy71;

			case '"':
				goto yy73;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy73:
		yych = *++YYCURSOR;

		switch (yych) {
			case '&':
				goto yy74;

			default:
				goto yy56;
		}

yy74:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'G':
			case 'g':
				goto yy75;

			default:
				goto yy56;
		}

yy75:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy76;

			default:
				goto yy56;
		}

yy76:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy77;

			default:
				goto yy56;
		}

yy77:
		yych = *++YYCURSOR;

		switch (yych) {
			case '&':
				goto yy78;

			default:
				goto yy56;
		}

yy78:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'G':
			case 'g':
				goto yy79;

			default:
				goto yy56;
		}

yy79:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy80;

			default:
				goto yy56;
		}

yy80:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy81;

			default:
				goto yy56;
		}

yy81:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy83;

			case 'P':
			case 'p':
				goto yy82;

			default:
				goto yy56;
		}

yy82:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'R':
			case 'r':
				goto yy105;

			default:
				goto yy56;
		}

yy83:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy84;

			default:
				goto yy56;
		}

yy84:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy85;

			default:
				goto yy56;
		}

yy85:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'A':
			case 'a':
				goto yy86;

			default:
				goto yy56;
		}

yy86:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'D':
			case 'd':
				goto yy87;

			default:
				goto yy56;
		}

yy87:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'A':
			case 'a':
				goto yy88;

			default:
				goto yy56;
		}

yy88:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy89;

			default:
				goto yy56;
		}

yy89:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'A':
			case 'a':
				goto yy90;

			default:
				goto yy56;
		}

yy90:
		yych = *++YYCURSOR;

		switch (yych) {
			case '&':
				goto yy91;

			default:
				goto yy56;
		}

yy91:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy92;

			default:
				goto yy56;
		}

yy92:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy93;

			default:
				goto yy56;
		}

yy93:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy94;

			default:
				goto yy56;
		}

yy94:
		yych = *++YYCURSOR;

		switch (yych) {
			case '&':
				goto yy95;

			default:
				goto yy56;
		}

yy95:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy96;

			default:
				goto yy56;
		}

yy96:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy97;

			default:
				goto yy56;
		}

yy97:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy98;

			default:
				goto yy56;
		}

yy98:
		yych = *++YYCURSOR;

		switch (yych) {
			case '"':
				goto yy99;

			default:
				goto yy56;
		}

yy99:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy99;

			case '\r':
				goto yy103;

			case '/':
				goto yy57;

			case '>':
				goto yy101;

			default:
				goto yy55;
		}

yy101:
		++YYCURSOR;
		{
			return OPML_OUTLINE_METADATA;
		}
yy103:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy99;

			case '\r':
				goto yy103;

			case '/':
				goto yy57;

			case '>':
				goto yy101;

			default:
				goto yy55;
		}

yy105:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy106;

			default:
				goto yy56;
		}

yy106:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'A':
			case 'a':
				goto yy107;

			default:
				goto yy56;
		}

yy107:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy108;

			default:
				goto yy56;
		}

yy108:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'B':
			case 'b':
				goto yy109;

			default:
				goto yy56;
		}

yy109:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy110;

			default:
				goto yy56;
		}

yy110:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy111;

			default:
				goto yy56;
		}

yy111:
		yych = *++YYCURSOR;

		switch (yych) {
			case '&':
				goto yy112;

			default:
				goto yy56;
		}

yy112:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy113;

			default:
				goto yy56;
		}

yy113:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy114;

			default:
				goto yy56;
		}

yy114:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy115;

			default:
				goto yy56;
		}

yy115:
		yych = *++YYCURSOR;

		switch (yych) {
			case '&':
				goto yy116;

			default:
				goto yy56;
		}

yy116:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy117;

			default:
				goto yy56;
		}

yy117:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy118;

			default:
				goto yy56;
		}

yy118:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy119;

			default:
				goto yy56;
		}

yy119:
		yych = *++YYCURSOR;

		switch (yych) {
			case '"':
				goto yy120;

			default:
				goto yy56;
		}

yy120:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy120;

			case '\r':
				goto yy122;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			case '_':
				goto yy124;

			default:
				goto yy55;
		}

yy122:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy120;

			case '\r':
				goto yy122;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			case '_':
				goto yy124;

			default:
				goto yy55;
		}

yy124:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'N':
			case 'n':
				goto yy125;

			default:
				goto yy56;
		}

yy125:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'O':
			case 'o':
				goto yy126;

			default:
				goto yy56;
		}

yy126:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy127;

			default:
				goto yy56;
		}

yy127:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy128;

			default:
				goto yy56;
		}

yy128:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy128;

			case '\r':
				goto yy130;

			case '/':
				goto yy57;

			case '=':
				goto yy132;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy130:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy128;

			case '\r':
				goto yy130;

			case '/':
				goto yy57;

			case '=':
				goto yy132;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy132:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy132;

			case '\r':
				goto yy134;

			case '"':
				goto yy136;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy134:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy132;

			case '\r':
				goto yy134;

			case '"':
				goto yy136;

			case '/':
				goto yy57;

			case '>':
				goto yy59;

			default:
				goto yy55;
		}

yy136:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '"':
				goto yy141;

			case '/':
				goto yy138;

			case '>':
				goto yy140;

			default:
				goto yy136;
		}

yy138:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '"':
				goto yy141;

			case '/':
				goto yy138;

			case '>':
				goto yy154;

			default:
				goto yy136;
		}

yy140:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		if (yych <= 0x00) {
			goto yy60;
		}

		goto yy150;
yy141:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy141;

			case '\r':
				goto yy145;

			case '/':
				goto yy57;

			case '>':
				goto yy143;

			default:
				goto yy55;
		}

yy143:
		++YYCURSOR;
yy144: {
			return OPML_OUTLINE_PREAMBLE;
		}
yy145:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '\t':
			case '\n':
			case ' ':
				goto yy141;

			case '\r':
				goto yy145;

			case '/':
				goto yy57;

			case '>':
				goto yy143;

			default:
				goto yy55;
		}

yy147:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
			case '\n':
			case ' ':
				goto yy147;

			case '\r':
				goto yy151;

			case '>':
				goto yy153;

			default:
				goto yy13;
		}

yy149:
		++YYCURSOR;
		yych = *YYCURSOR;
yy150:

		switch (yych) {
			case 0x00:
				goto yy13;

			case '"':
				goto yy147;

			default:
				goto yy149;
		}

yy151:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
			case '\n':
			case ' ':
				goto yy147;

			case '\r':
				goto yy151;

			case '>':
				goto yy153;

			default:
				goto yy13;
		}

yy153:
		yych = *++YYCURSOR;
		goto yy144;
yy154:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);

		if (yych <= 0x00) {
			goto yy62;
		}

		goto yy150;
yy155:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy156;

			default:
				goto yy13;
		}

yy156:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0x00:
				goto yy13;

			case '>':
				goto yy158;

			default:
				goto yy156;
		}

yy158:
		++YYCURSOR;
		{
			return OPML_OPML_OPEN;
		}
yy160:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'P':
			case 'p':
				goto yy181;

			case 'U':
			case 'u':
				goto yy180;

			default:
				goto yy13;
		}

yy161:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy175;

			default:
				goto yy13;
		}

yy162:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'I':
			case 'i':
				goto yy169;

			default:
				goto yy13;
		}

yy163:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'O':
			case 'o':
				goto yy164;

			default:
				goto yy13;
		}

yy164:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'D':
			case 'd':
				goto yy165;

			default:
				goto yy13;
		}

yy165:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'Y':
			case 'y':
				goto yy166;

			default:
				goto yy13;
		}

yy166:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy167;

			default:
				goto yy13;
		}

yy167:
		++YYCURSOR;
		{
			return OPML_BODY_CLOSE;
		}
yy169:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy170;

			default:
				goto yy13;
		}

yy170:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy171;

			default:
				goto yy13;
		}

yy171:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy172;

			default:
				goto yy13;
		}

yy172:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy173;

			default:
				goto yy13;
		}

yy173:
		++YYCURSOR;
		{
			return OPML_TITLE_CLOSE;
		}
yy175:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'A':
			case 'a':
				goto yy176;

			default:
				goto yy13;
		}

yy176:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'D':
			case 'd':
				goto yy177;

			default:
				goto yy13;
		}

yy177:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy178;

			default:
				goto yy13;
		}

yy178:
		++YYCURSOR;
		{
			return OPML_HEAD_CLOSE;
		}
yy180:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'T':
			case 't':
				goto yy186;

			default:
				goto yy13;
		}

yy181:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy182;

			default:
				goto yy13;
		}

yy182:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy183;

			default:
				goto yy13;
		}

yy183:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy184;

			default:
				goto yy13;
		}

yy184:
		++YYCURSOR;
		{
			return OPML_OPML_CLOSE;
		}
yy186:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'L':
			case 'l':
				goto yy187;

			default:
				goto yy13;
		}

yy187:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'I':
			case 'i':
				goto yy188;

			default:
				goto yy13;
		}

yy188:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'N':
			case 'n':
				goto yy189;

			default:
				goto yy13;
		}

yy189:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'E':
			case 'e':
				goto yy190;

			default:
				goto yy13;
		}

yy190:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy191;

			default:
				goto yy13;
		}

yy191:
		++YYCURSOR;
		{
			return OPML_OUTLINE_CLOSE;
		}
	}

}
