#define LINE_HR                          1
#define LINE_SETEXT_1                    2
#define LINE_SETEXT_2                    3
#define LINE_CONTINUATION                4
#define LINE_PLAIN                       5
#define LINE_INDENTED_TAB                6
#define LINE_INDENTED_SPACE              7
#define LINE_TABLE                       8
#define LINE_TABLE_SEPARATOR             9
#define LINE_FALLBACK                   10
#define LINE_HTML                       11
#define LINE_ATX_1                      12
#define LINE_ATX_2                      13
#define LINE_ATX_3                      14
#define LINE_ATX_4                      15
#define LINE_ATX_5                      16
#define LINE_ATX_6                      17
#define LINE_BLOCKQUOTE                 18
#define LINE_LIST_BULLETED              19
#define LINE_LIST_ENUMERATED            20
#define LINE_DEF_ABBREVIATION           21
#define LINE_DEF_CITATION               22
#define LINE_DEF_FOOTNOTE               23
#define LINE_DEF_GLOSSARY               24
#define LINE_DEF_LINK                   25
#define LINE_TOC                        26
#define LINE_DEFINITION                 27
#define LINE_META                       28
#define LINE_BACKTICK                   29
#define LINE_FENCE_BACKTICK_3           30
#define LINE_FENCE_BACKTICK_4           31
#define LINE_FENCE_BACKTICK_5           32
#define LINE_FENCE_BACKTICK_START_3     33
#define LINE_FENCE_BACKTICK_START_4     34
#define LINE_FENCE_BACKTICK_START_5     35
#define LINE_STOP_COMMENT               36
#define LINE_EMPTY                      37
#define LINE_START_COMMENT              38
