#define LINE_HR                          1
#define LINE_SETEXT_1                    2
#define LINE_SETEXT_2                    3
#define LINE_PLAIN                       4
#define LINE_TABLE_SEPARATOR             5
#define LINE_CONTINUATION                6
#define LINE_INDENTED_TAB                7
#define LINE_INDENTED_SPACE              8
#define LINE_TABLE                       9
#define LINE_HTML                       10
#define LINE_ATX_1                      11
#define LINE_ATX_2                      12
#define LINE_ATX_3                      13
#define LINE_ATX_4                      14
#define LINE_ATX_5                      15
#define LINE_ATX_6                      16
#define LINE_BLOCKQUOTE                 17
#define LINE_LIST_BULLETED              18
#define LINE_LIST_ENUMERATED            19
#define LINE_DEF_ABBREVIATION           20
#define LINE_DEF_CITATION               21
#define LINE_DEF_FOOTNOTE               22
#define LINE_DEF_GLOSSARY               23
#define LINE_DEF_LINK                   24
#define LINE_FENCE_BACKTICK             25
#define LINE_FENCE_BACKTICK_START       26
#define LINE_TOC                        27
#define LINE_DEFINITION                 28
#define LINE_EMPTY                      29
#define LINE_FENCE_BACKTICK_3           30
#define LINE_FENCE_BACKTICK_4           31
#define LINE_FENCE_BACKTICK_5           32
#define LINE_FENCE_BACKTICK_START_3     33
#define LINE_FENCE_BACKTICK_START_4     34
#define LINE_FENCE_BACKTICK_START_5     35
#define LINE_META                       36
