#!/bin/sh

# This command can be run any time to ensure that all submodules are on
# the most recent commit for the configured branch, as set up
# in the `link_git_modules` script.

re2c -i -8 lexer.re > lexer.c

re2c -i -8 scanners.re > scanners.c

# It seems that some other versions of lemon don't create valid 
# parsers?? Using the version included here works
# lemon -l parser.y
../../lemon/build/lemon -l parser.y
