/* Generated by re2c 1.3 on Tue Jul 13 11:09:27 2021 */
/**

	MultiMarkdown 6 -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file lexer.re

	@brief Description of the regular expressions used to define tokens,
	used by re2c to create a lexer/tokenizer.


	@author	Fletcher T. Penney
	@bug

**/

/*

	Copyright © 2016 - 2017 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..

	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:

		https://github.com/fletcher/MultiMarkdown-4/

	MMD 4 is released under both the MIT License and GPL.


	CuTest is released under the zlib/libpng license. See CuTest.c for the text
	of the license.


	## The MIT License ##

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

*/

#include "lexer.h"
#include "libMultiMarkdown.h"
#include "parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int scan(Scanner * s, const char * stop) {

scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;


	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy4;

			case '\n':
				goto yy6;

			case '\r':
				goto yy8;

			case ' ':
				goto yy9;

			case '!':
				goto yy10;

			case '"':
				goto yy11;

			case '#':
				goto yy13;

			case '$':
				goto yy15;

			case '%':
				goto yy17;

			case '&':
				goto yy19;

			case '\'':
				goto yy21;

			case '(':
				goto yy23;

			case ')':
				goto yy25;

			case '*':
				goto yy27;

			case '+':
				goto yy29;

			case '-':
				goto yy31;

			case '.':
				goto yy33;

			case '/':
				goto yy34;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy36;

			case ':':
				goto yy37;

			case '<':
				goto yy39;

			case '=':
				goto yy41;

			case '>':
				goto yy43;

			case '[':
				goto yy45;

			case '\\':
				goto yy47;

			case ']':
				goto yy49;

			case '^':
				goto yy51;

			case '_':
				goto yy53;

			case '`':
				goto yy55;

			case '{':
				goto yy58;

			case '|':
				goto yy60;

			case '}':
				goto yy63;

			case '~':
				goto yy65;

			case 0xC2:
				goto yy67;

			case 0xEF:
				goto yy68;

			default:
				goto yy2;
		}

yy2:
		++YYCURSOR;
yy3: {
			goto scan;
		}
yy4:
		++YYCURSOR;
		{
			return INDENT_TAB;
		}
yy6:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy69;

			default:
				goto yy7;
		}

yy7: {
			return TEXT_NL;
		}
yy8:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy6;

			case ' ':
				goto yy69;

			default:
				goto yy7;
		}

yy9:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\t':
				goto yy71;

			case '\n':
				goto yy73;

			case '\r':
				goto yy74;

			case ' ':
				goto yy75;

			case 0xC2:
				goto yy77;

			default:
				goto yy3;
		}

yy10:
		yych = *++YYCURSOR;

		switch (yych) {
			case '[':
				goto yy78;

			default:
				goto yy3;
		}

yy11:
		++YYCURSOR;
		{
			return QUOTE_DOUBLE;
		}
yy13:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy80;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy82;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy85;

			case '#':
				goto yy86;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy87;

			default:
				goto yy14;
		}

yy14: {
			return TEXT_HASH;
		}
yy15:
		yych = *++YYCURSOR;

		switch (yych) {
			case '$':
				goto yy88;

			default:
				goto yy16;
		}

yy16: {
			return MATH_DOLLAR_SINGLE;
		}
yy17:
		++YYCURSOR;
		{
			return TEXT_PERCENT;
		}
yy19:
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '#':
				goto yy90;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
				goto yy91;

			case 'A':
			case 'a':
				goto yy93;

			default:
				goto yy20;
		}

yy20: {
			return AMPERSAND;
		}
yy21:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\'':
				goto yy94;

			default:
				goto yy22;
		}

yy22: {
			return QUOTE_SINGLE;
		}
yy23:
		++YYCURSOR;
		{
			return PAREN_LEFT;
		}
yy25:
		++YYCURSOR;
		{
			return PAREN_RIGHT;
		}
yy27:
		++YYCURSOR;
		{
			return STAR;
		}
yy29:
		yyaccept = 4;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '+':
				goto yy96;

			default:
				goto yy30;
		}

yy30: {
			return PLUS;
		}
yy31:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy97;

			default:
				goto yy32;
		}

yy32: {
			return DASH_N;
		}
yy33:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy99;

			case '.':
				goto yy100;

			default:
				goto yy3;
		}

yy34:
		++YYCURSOR;
		{
			return SLASH;
		}
yy36:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '.':
				goto yy101;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy102;

			default:
				goto yy3;
		}

yy37:
		++YYCURSOR;
		{
			return COLON;
		}
yy39:
		yyaccept = 5;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '!':
				goto yy104;

			case '<':
				goto yy105;

			default:
				goto yy40;
		}

yy40: {
			return ANGLE_LEFT;
		}
yy41:
		yyaccept = 6;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '=':
				goto yy106;

			default:
				goto yy42;
		}

yy42: {
			return EQUAL;
		}
yy43:
		++YYCURSOR;
		{
			return ANGLE_RIGHT;
		}
yy45:
		yych = *++YYCURSOR;

		switch (yych) {
			case '#':
				goto yy107;

			case '%':
				goto yy109;

			case '>':
				goto yy111;

			case '?':
				goto yy113;

			case '[':
				goto yy115;

			case '^':
				goto yy117;

			default:
				goto yy46;
		}

yy46: {
			return BRACKET_LEFT;
		}
yy47:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy119;

			case '\r':
				goto yy121;

			case ' ':
				goto yy122;

			case '!':
				goto yy124;

			case '"':
				goto yy126;

			case '#':
				goto yy128;

			case '$':
				goto yy130;

			case '%':
				goto yy132;

			case '&':
				goto yy134;

			case '\'':
				goto yy136;

			case '(':
				goto yy138;

			case ')':
				goto yy140;

			case '*':
				goto yy142;

			case '+':
				goto yy144;

			case ',':
				goto yy146;

			case '-':
				goto yy148;

			case '.':
				goto yy150;

			case '/':
				goto yy152;

			case ':':
				goto yy154;

			case ';':
				goto yy156;

			case '<':
				goto yy158;

			case '=':
				goto yy160;

			case '>':
				goto yy162;

			case '?':
				goto yy164;

			case '@':
				goto yy166;

			case '[':
				goto yy168;

			case '\\':
				goto yy170;

			case ']':
				goto yy172;

			case '^':
				goto yy174;

			case '_':
				goto yy176;

			case '`':
				goto yy178;

			case '{':
				goto yy180;

			case '|':
				goto yy182;

			case '}':
				goto yy184;

			case '~':
				goto yy186;

			default:
				goto yy48;
		}

yy48: {
			return TEXT_BACKSLASH;
		}
yy49:
		yych = *++YYCURSOR;

		switch (yych) {
			case ']':
				goto yy188;

			default:
				goto yy50;
		}

yy50: {
			return BRACKET_RIGHT;
		}
yy51:
		++YYCURSOR;
		{
			return SUPERSCRIPT;
		}
yy53:
		++YYCURSOR;
		{
			return UL;
		}
yy55:
		yych = *++YYCURSOR;

		switch (yych) {
			case '`':
				goto yy55;

			default:
				goto yy57;
		}

yy57: {
			return BACKTICK;
		}
yy58:
		yyaccept = 7;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '+':
				goto yy190;

			case '-':
				goto yy191;

			case '=':
				goto yy192;

			case '>':
				goto yy194;

			case '{':
				goto yy195;

			case '~':
				goto yy197;

			default:
				goto yy59;
		}

yy59: {
			return TEXT_BRACE_LEFT;
		}
yy60:
		yych = *++YYCURSOR;

		switch (yych) {
			case '|':
				goto yy60;

			default:
				goto yy62;
		}

yy62: {
			return PIPE;
		}
yy63:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy198;

			default:
				goto yy64;
		}

yy64: {
			return TEXT_BRACE_RIGHT;
		}
yy65:
		yyaccept = 8;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '>':
				goto yy200;

			case '~':
				goto yy202;

			default:
				goto yy66;
		}

yy66: {
			return SUBSCRIPT;
		}
yy67:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0xA0:
				goto yy203;

			default:
				goto yy3;
		}

yy68:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0xBF:
				goto yy204;

			default:
				goto yy3;
		}

yy69:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\v':
			case '\f':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				YYCTXMARKER = YYCURSOR;
				goto yy205;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				YYCTXMARKER = YYCURSOR;
				goto yy207;

			case 0xE0:
				YYCTXMARKER = YYCURSOR;
				goto yy208;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				YYCTXMARKER = YYCURSOR;
				goto yy209;

			case 0xF0:
				YYCTXMARKER = YYCURSOR;
				goto yy210;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				YYCTXMARKER = YYCURSOR;
				goto yy211;

			case 0xF4:
				YYCTXMARKER = YYCURSOR;
				goto yy212;

			default:
				goto yy70;
		}

yy70:
		YYCURSOR = YYMARKER;

		switch (yyaccept) {
			case 0:
				goto yy7;

			case 1:
				goto yy3;

			case 2:
				goto yy14;

			case 3:
				goto yy20;

			case 4:
				goto yy30;

			case 5:
				goto yy40;

			case 6:
				goto yy42;

			case 7:
				goto yy59;

			case 8:
				goto yy66;

			case 9:
				goto yy76;

			case 10:
				goto yy84;

			case 11:
				goto yy196;

			case 12:
				goto yy214;

			case 13:
				goto yy222;

			case 14:
				goto yy245;

			case 15:
				goto yy279;

			case 16:
				goto yy285;

			case 17:
				goto yy313;

			case 18:
				goto yy328;

			default:
				goto yy338;
		}

yy71:
		++YYCURSOR;
		YYCURSOR -= 1;
		{
			return NON_INDENT_SPACE;
		}
yy73:
		++YYCURSOR;
		goto yy7;
yy74:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy73;

			default:
				goto yy7;
		}

yy75:
		yyaccept = 9;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy213;

			case '\r':
				goto yy215;

			case ' ':
				goto yy216;

			case 0xC2:
				goto yy217;

			default:
				goto yy76;
		}

yy76: {
			return NON_INDENT_SPACE;
		}
yy77:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy75;

			default:
				goto yy70;
		}

yy78:
		++YYCURSOR;
		{
			return BRACKET_IMAGE_LEFT;
		}
yy80:
		++YYCURSOR;
yy81:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH1;
		}
yy82:
		yyaccept = 10;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy80;

			case '\t':
			case ' ':
				goto yy82;

			case '\r':
				goto yy85;

			case 0xC2:
				goto yy87;

			default:
				goto yy84;
		}

yy84: {
			return HASH1;
		}
yy85:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy80;

			default:
				goto yy81;
		}

yy86:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy218;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy220;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy223;

			case '#':
				goto yy224;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy225;

			default:
				goto yy70;
		}

yy87:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy82;

			default:
				goto yy70;
		}

yy88:
		++YYCURSOR;
		{
			return MATH_DOLLAR_DOUBLE;
		}
yy90:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy226;

			case 'X':
			case 'x':
				goto yy228;

			default:
				goto yy70;
		}

yy91:
		yych = *++YYCURSOR;
yy92:

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
				goto yy91;

			case ';':
				goto yy229;

			default:
				goto yy70;
		}

yy93:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy231;

			default:
				goto yy92;
		}

yy94:
		++YYCURSOR;
		{
			return QUOTE_RIGHT_ALT;
		}
yy96:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy232;

			default:
				goto yy70;
		}

yy97:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy234;

			case '>':
				goto yy236;

			case '}':
				goto yy238;

			default:
				goto yy98;
		}

yy98: {
			return DASH_N;
		}
yy99:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy240;

			default:
				goto yy70;
		}

yy100:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy241;

			default:
				goto yy70;
		}

yy101:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy243;

			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy246;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy247;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy248;

			default:
				goto yy70;
		}

yy102:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy101;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy102;

			default:
				goto yy70;
		}

yy104:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy249;

			default:
				goto yy70;
		}

yy105:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy250;

			default:
				goto yy70;
		}

yy106:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy252;

			default:
				goto yy70;
		}

yy107:
		++YYCURSOR;
		{
			return BRACKET_CITATION_LEFT;
		}
yy109:
		++YYCURSOR;
		{
			return BRACKET_VARIABLE_LEFT;
		}
yy111:
		++YYCURSOR;
		{
			return BRACKET_ABBREVIATION_LEFT;
		}
yy113:
		++YYCURSOR;
		{
			return BRACKET_GLOSSARY_LEFT;
		}
yy115:
		++YYCURSOR;
		{
			return BRACKET_DOUBLE_LEFT;
		}
yy117:
		++YYCURSOR;
		{
			return BRACKET_FOOTNOTE_LEFT;
		}
yy119:
		++YYCURSOR;
yy120: {
			return TEXT_LINEBREAK;
		}
yy121:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy119;

			default:
				goto yy120;
		}

yy122:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy124:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy126:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy128:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy130:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy132:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy134:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy136:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy138:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy140:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy142:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy144:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy146:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy148:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy150:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy152:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy154:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy156:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy158:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy160:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy162:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy164:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy166:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy168:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy170:
		yych = *++YYCURSOR;

		switch (yych) {
			case '(':
				goto yy254;

			case ')':
				goto yy256;

			case '[':
				goto yy258;

			case ']':
				goto yy260;

			default:
				goto yy171;
		}

yy171: {
			return ESCAPED_CHARACTER;
		}
yy172:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy174:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy176:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy178:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy180:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy182:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy184:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy186:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy188:
		++YYCURSOR;
		{
			return BRACKET_DOUBLE_RIGHT;
		}
yy190:
		yych = *++YYCURSOR;

		switch (yych) {
			case '+':
				goto yy262;

			default:
				goto yy70;
		}

yy191:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy264;

			default:
				goto yy70;
		}

yy192:
		yych = *++YYCURSOR;

		switch (yych) {
			case '=':
				goto yy266;

			default:
				goto yy193;
		}

yy193: {
			return RAW_FILTER_LEFT;
		}
yy194:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy268;

			default:
				goto yy70;
		}

yy195:
		yyaccept = 11;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 'T':
				goto yy270;

			default:
				goto yy196;
		}

yy196: {
			return BRACE_DOUBLE_LEFT;
		}
yy197:
		yych = *++YYCURSOR;

		switch (yych) {
			case '~':
				goto yy271;

			default:
				goto yy70;
		}

yy198:
		++YYCURSOR;
		{
			return BRACE_DOUBLE_RIGHT;
		}
yy200:
		++YYCURSOR;
		{
			return CRITIC_SUB_DIV;
		}
yy202:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy273;

			default:
				goto yy70;
		}

yy203:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy71;

			case ' ':
				goto yy75;

			case 0xC2:
				goto yy77;

			default:
				goto yy70;
		}

yy204:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xBC:
				goto yy275;

			default:
				goto yy70;
		}

yy205:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_NL_SP;
		}
yy207:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy205;

			default:
				goto yy70;
		}

yy208:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy207;

			default:
				goto yy70;
		}

yy209:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy207;

			default:
				goto yy70;
		}

yy210:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy209;

			default:
				goto yy70;
		}

yy211:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy209;

			default:
				goto yy70;
		}

yy212:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy209;

			default:
				goto yy70;
		}

yy213:
		yyaccept = 12;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy277;

			default:
				goto yy214;
		}

yy214: {
			return TEXT_LINEBREAK;
		}
yy215:
		yyaccept = 12;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy213;

			case ' ':
				goto yy277;

			default:
				goto yy214;
		}

yy216:
		yyaccept = 9;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy213;

			case '\r':
				goto yy215;

			case ' ':
				goto yy278;

			case 0xC2:
				goto yy280;

			default:
				goto yy76;
		}

yy217:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy216;

			default:
				goto yy70;
		}

yy218:
		++YYCURSOR;
yy219:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH2;
		}
yy220:
		yyaccept = 13;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy218;

			case '\t':
			case ' ':
				goto yy220;

			case '\r':
				goto yy223;

			case 0xC2:
				goto yy225;

			default:
				goto yy222;
		}

yy222: {
			return HASH2;
		}
yy223:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy218;

			default:
				goto yy219;
		}

yy224:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy281;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy283;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy286;

			case '#':
				goto yy287;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy288;

			default:
				goto yy70;
		}

yy225:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy220;

			default:
				goto yy70;
		}

yy226:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy226;

			case ';':
				goto yy289;

			default:
				goto yy70;
		}

yy228:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy70;

			default:
				goto yy292;
		}

yy229:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy231:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'P':
			case 'p':
				goto yy293;

			default:
				goto yy92;
		}

yy232:
		++YYCURSOR;
		{
			return CRITIC_ADD_CLOSE;
		}
yy234:
		++YYCURSOR;
		{
			return DASH_M;
		}
yy236:
		++YYCURSOR;
		{
			return HTML_COMMENT_STOP;
		}
yy238:
		++YYCURSOR;
		{
			return CRITIC_DEL_CLOSE;
		}
yy240:
		yych = *++YYCURSOR;

		switch (yych) {
			case ' ':
				goto yy294;

			default:
				goto yy70;
		}

yy241:
		++YYCURSOR;
		{
			return ELLIPSIS;
		}
yy243:
		yyaccept = 14;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\t':
			case ' ':
				goto yy243;

			case 0xC2:
				goto yy248;

			default:
				goto yy245;
		}

yy245:
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_NUMBER_POSS_LIST;
		}
yy246:
		++YYCURSOR;
		goto yy245;
yy247:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy246;

			default:
				goto yy245;
		}

yy248:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy243;

			default:
				goto yy70;
		}

yy249:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy295;

			default:
				goto yy70;
		}

yy250:
		++YYCURSOR;
		{
			return CRITIC_COM_CLOSE;
		}
yy252:
		++YYCURSOR;
		{
			return CRITIC_HI_CLOSE;
		}
yy254:
		++YYCURSOR;
		{
			return MATH_PAREN_OPEN;
		}
yy256:
		++YYCURSOR;
		{
			return MATH_PAREN_CLOSE;
		}
yy258:
		++YYCURSOR;
		{
			return MATH_BRACKET_OPEN;
		}
yy260:
		++YYCURSOR;
		{
			return MATH_BRACKET_CLOSE;
		}
yy262:
		++YYCURSOR;
		{
			return CRITIC_ADD_OPEN;
		}
yy264:
		++YYCURSOR;
		{
			return CRITIC_DEL_OPEN;
		}
yy266:
		++YYCURSOR;
		{
			return CRITIC_HI_OPEN;
		}
yy268:
		++YYCURSOR;
		{
			return CRITIC_COM_OPEN;
		}
yy270:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'O':
				goto yy297;

			default:
				goto yy70;
		}

yy271:
		++YYCURSOR;
		{
			return CRITIC_SUB_OPEN;
		}
yy273:
		++YYCURSOR;
		{
			return CRITIC_SUB_CLOSE;
		}
yy275:
		++YYCURSOR;
		{
			return OBJECT_REPLACEMENT_CHARACTER;
		}
yy277:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\v':
			case '\f':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				YYCTXMARKER = YYCURSOR;
				goto yy298;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				YYCTXMARKER = YYCURSOR;
				goto yy300;

			case 0xE0:
				YYCTXMARKER = YYCURSOR;
				goto yy301;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				YYCTXMARKER = YYCURSOR;
				goto yy302;

			case 0xF0:
				YYCTXMARKER = YYCURSOR;
				goto yy303;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				YYCTXMARKER = YYCURSOR;
				goto yy304;

			case 0xF4:
				YYCTXMARKER = YYCURSOR;
				goto yy305;

			default:
				goto yy70;
		}

yy278:
		yyaccept = 15;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy213;

			case '\r':
				goto yy215;

			case ' ':
				goto yy306;

			case 0xC2:
				goto yy308;

			default:
				goto yy279;
		}

yy279: {
			return INDENT_SPACE;
		}
yy280:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy278;

			default:
				goto yy70;
		}

yy281:
		++YYCURSOR;
yy282:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH3;
		}
yy283:
		yyaccept = 16;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy281;

			case '\t':
			case ' ':
				goto yy283;

			case '\r':
				goto yy286;

			case 0xC2:
				goto yy288;

			default:
				goto yy285;
		}

yy285: {
			return HASH3;
		}
yy286:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy281;

			default:
				goto yy282;
		}

yy287:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy309;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy311;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy314;

			case '#':
				goto yy315;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy316;

			default:
				goto yy70;
		}

yy288:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy283;

			default:
				goto yy70;
		}

yy289:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy291:
		yych = *++YYCURSOR;
yy292:

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
				goto yy291;

			case ';':
				goto yy317;

			default:
				goto yy70;
		}

yy293:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy319;

			default:
				goto yy92;
		}

yy294:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy321;

			default:
				goto yy70;
		}

yy295:
		++YYCURSOR;
		{
			return HTML_COMMENT_START;
		}
yy297:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'C':
				goto yy323;

			default:
				goto yy70;
		}

yy298:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_LINEBREAK_SP;
		}
yy300:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy298;

			default:
				goto yy70;
		}

yy301:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy300;

			default:
				goto yy70;
		}

yy302:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy300;

			default:
				goto yy70;
		}

yy303:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy302;

			default:
				goto yy70;
		}

yy304:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy302;

			default:
				goto yy70;
		}

yy305:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy302;

			default:
				goto yy70;
		}

yy306:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy213;

			case '\r':
				goto yy215;

			case ' ':
				goto yy306;

			case 0xC2:
				goto yy308;

			default:
				goto yy70;
		}

yy308:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy306;

			default:
				goto yy70;
		}

yy309:
		++YYCURSOR;
yy310:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH4;
		}
yy311:
		yyaccept = 17;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy309;

			case '\t':
			case ' ':
				goto yy311;

			case '\r':
				goto yy314;

			case 0xC2:
				goto yy316;

			default:
				goto yy313;
		}

yy313: {
			return HASH4;
		}
yy314:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy309;

			default:
				goto yy310;
		}

yy315:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy324;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy326;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy329;

			case '#':
				goto yy330;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy331;

			default:
				goto yy70;
		}

yy316:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy311;

			default:
				goto yy70;
		}

yy317:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy319:
		++YYCURSOR;
		{
			return AMPERSAND_LONG;
		}
yy321:
		++YYCURSOR;
		{
			return ELLIPSIS;
		}
yy323:
		yych = *++YYCURSOR;

		switch (yych) {
			case ':':
				goto yy332;

			case '}':
				goto yy333;

			default:
				goto yy70;
		}

yy324:
		++YYCURSOR;
yy325:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH5;
		}
yy326:
		yyaccept = 18;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy324;

			case '\t':
			case ' ':
				goto yy326;

			case '\r':
				goto yy329;

			case 0xC2:
				goto yy331;

			default:
				goto yy328;
		}

yy328: {
			return HASH5;
		}
yy329:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy324;

			default:
				goto yy325;
		}

yy330:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\n':
				YYCTXMARKER = YYCURSOR;
				goto yy334;

			case '\t':
			case ' ':
				YYCTXMARKER = YYCURSOR;
				goto yy336;

			case '\r':
				YYCTXMARKER = YYCURSOR;
				goto yy339;

			case 0xC2:
				YYCTXMARKER = YYCURSOR;
				goto yy340;

			default:
				goto yy70;
		}

yy331:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy326;

			default:
				goto yy70;
		}

yy332:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy341;

			default:
				goto yy70;
		}

yy333:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy342;

			default:
				goto yy70;
		}

yy334:
		++YYCURSOR;
yy335:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH6;
		}
yy336:
		yyaccept = 19;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy334;

			case '\t':
			case ' ':
				goto yy336;

			case '\r':
				goto yy339;

			case 0xC2:
				goto yy340;

			default:
				goto yy338;
		}

yy338: {
			return HASH6;
		}
yy339:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy334;

			default:
				goto yy335;
		}

yy340:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy336;

			default:
				goto yy70;
		}

yy341:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy344;

			case '}':
				goto yy345;

			default:
				goto yy70;
		}

yy342:
		++YYCURSOR;
		{
			return TOC;
		}
yy344:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy346;

			default:
				goto yy70;
		}

yy345:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy347;

			default:
				goto yy70;
		}

yy346:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy349;

			default:
				goto yy70;
		}

yy347:
		++YYCURSOR;
		{
			return TOC_SINGLE;
		}
yy349:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy350;

			default:
				goto yy70;
		}

yy350:
		++YYCURSOR;
		{
			return TOC_RANGE;
		}
	}

}
