/* Generated by re2c 0.15.3 on Sat Jul 10 22:20:04 2021 */
/**

	MultiMarkdown 6 -- Lightweight markup processor to produce HTML, LaTeX, and more.

	@file lexer.re

	@brief Description of the regular expressions used to define tokens,
	used by re2c to create a lexer/tokenizer.


	@author	Fletcher T. Penney
	@bug

**/

/*

	Copyright © 2016 - 2017 Fletcher T. Penney.


	The `MultiMarkdown 6` project is released under the MIT License..

	GLibFacade.c and GLibFacade.h are from the MultiMarkdown v4 project:

		https://github.com/fletcher/MultiMarkdown-4/

	MMD 4 is released under both the MIT License and GPL.


	CuTest is released under the zlib/libpng license. See CuTest.c for the text
	of the license.


	## The MIT License ##

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.

*/

#include "lexer.h"
#include "libMultiMarkdown.h"
#include "parser.h"


// Basic scanner struct

#define YYCTYPE		unsigned char
#define YYCURSOR	s->cur
#define YYMARKER	s->ptr
#define YYCTXMARKER	s->ctx

int scan(Scanner * s, const char * stop) {

scan:

	if (s->cur >= stop) {
		return 0;
	}

	s->start = s->cur;


	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy4;

			case '\n':
				goto yy6;

			case '\r':
				goto yy8;

			case ' ':
				goto yy9;

			case '!':
				goto yy10;

			case '"':
				goto yy11;

			case '#':
				goto yy13;

			case '$':
				goto yy15;

			case '%':
				goto yy17;

			case '&':
				goto yy19;

			case '\'':
				goto yy21;

			case '(':
				goto yy23;

			case ')':
				goto yy25;

			case '*':
				goto yy27;

			case '+':
				goto yy29;

			case '-':
				goto yy31;

			case '.':
				goto yy33;

			case '/':
				goto yy34;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy36;

			case ':':
				goto yy37;

			case '<':
				goto yy39;

			case '=':
				goto yy41;

			case '>':
				goto yy43;

			case '[':
				goto yy45;

			case '\\':
				goto yy47;

			case ']':
				goto yy49;

			case '^':
				goto yy51;

			case '_':
				goto yy53;

			case '`':
				goto yy55;

			case '{':
				goto yy57;

			case '|':
				goto yy59;

			case '}':
				goto yy61;

			case '~':
				goto yy63;

			case 0xC2:
				goto yy65;

			case 0xEF:
				goto yy66;

			default:
				goto yy2;
		}

yy2:
		++YYCURSOR;
yy3: {
			goto scan;
		}
yy4:
		++YYCURSOR;
		{
			return INDENT_TAB;
		}
yy6:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy342;

			default:
				goto yy7;
		}

yy7: {
			return TEXT_NL;
		}
yy8:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy341;

			case ' ':
				goto yy342;

			default:
				goto yy7;
		}

yy9:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy75;

			case '\n':
				goto yy339;

			case '\r':
				goto yy340;

			case ' ':
				goto yy72;

			case 0xC2:
				goto yy74;

			default:
				goto yy3;
		}

yy10:
		yych = *++YYCURSOR;

		switch (yych) {
			case '[':
				goto yy337;

			default:
				goto yy3;
		}

yy11:
		++YYCURSOR;
		{
			return QUOTE_DOUBLE;
		}
yy13:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\t':
			case '\n':
			case '\r':
			case ' ':
			case 0xC2:
				goto yy292;

			case '#':
				goto yy290;

			default:
				goto yy14;
		}

yy14: {
			return TEXT_HASH;
		}
yy15:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '$':
				goto yy288;

			default:
				goto yy16;
		}

yy16: {
			return MATH_DOLLAR_SINGLE;
		}
yy17:
		++YYCURSOR;
		{
			return TEXT_PERCENT;
		}
yy19:
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '#':
				goto yy272;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
				goto yy269;

			case 'A':
			case 'a':
				goto yy271;

			default:
				goto yy20;
		}

yy20: {
			return AMPERSAND;
		}
yy21:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '\'':
				goto yy267;

			default:
				goto yy22;
		}

yy22: {
			return QUOTE_SINGLE;
		}
yy23:
		++YYCURSOR;
		{
			return PAREN_LEFT;
		}
yy25:
		++YYCURSOR;
		{
			return PAREN_RIGHT;
		}
yy27:
		++YYCURSOR;
		{
			return STAR;
		}
yy29:
		yyaccept = 4;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '+':
				goto yy264;

			default:
				goto yy30;
		}

yy30: {
			return PLUS;
		}
yy31:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '-':
				goto yy256;

			default:
				goto yy32;
		}

yy32: {
			return DASH_N;
		}
yy33:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy248;

			case '.':
				goto yy249;

			default:
				goto yy3;
		}

yy34:
		++YYCURSOR;
		{
			return SLASH;
		}
yy36:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '.':
				goto yy239;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy240;

			default:
				goto yy3;
		}

yy37:
		++YYCURSOR;
		{
			return COLON;
		}
yy39:
		yyaccept = 5;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '!':
				goto yy232;

			case '<':
				goto yy233;

			default:
				goto yy40;
		}

yy40: {
			return ANGLE_LEFT;
		}
yy41:
		yyaccept = 6;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '=':
				goto yy229;

			default:
				goto yy42;
		}

yy42: {
			return EQUAL;
		}
yy43:
		++YYCURSOR;
		{
			return ANGLE_RIGHT;
		}
yy45:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '#':
				goto yy225;

			case '%':
				goto yy219;

			case '>':
				goto yy227;

			case '?':
				goto yy221;

			case '^':
				goto yy223;

			default:
				goto yy46;
		}

yy46: {
			return BRACKET_LEFT;
		}
yy47:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '\n':
				goto yy142;

			case '\r':
				goto yy144;

			case ' ':
				goto yy147;

			case '!':
				goto yy207;

			case '"':
				goto yy197;

			case '#':
				goto yy177;

			case '$':
				goto yy175;

			case '%':
				goto yy173;

			case '&':
				goto yy161;

			case '\'':
				goto yy195;

			case '(':
				goto yy189;

			case ')':
				goto yy187;

			case '*':
				goto yy153;

			case '+':
				goto yy171;

			case ',':
				goto yy203;

			case '-':
				goto yy169;

			case '.':
				goto yy209;

			case '/':
				goto yy157;

			case ':':
				goto yy199;

			case ';':
				goto yy201;

			case '<':
				goto yy165;

			case '=':
				goto yy167;

			case '>':
				goto yy163;

			case '?':
				goto yy205;

			case '@':
				goto yy159;

			case '[':
				goto yy181;

			case '\\':
				goto yy145;

			case ']':
				goto yy179;

			case '^':
				goto yy155;

			case '_':
				goto yy151;

			case '`':
				goto yy193;

			case '{':
				goto yy185;

			case '|':
				goto yy149;

			case '}':
				goto yy183;

			case '~':
				goto yy191;

			default:
				goto yy48;
		}

yy48: {
			return TEXT_BACKSLASH;
		}
yy49:
		++YYCURSOR;
		{
			return BRACKET_RIGHT;
		}
yy51:
		++YYCURSOR;
		{
			return SUPERSCRIPT;
		}
yy53:
		++YYCURSOR;
		{
			return UL;
		}
yy55:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy141;
yy56: {
			return BACKTICK;
		}
yy57:
		yyaccept = 7;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '+':
				goto yy113;

			case '-':
				goto yy112;

			case '=':
				goto yy106;

			case '>':
				goto yy111;

			case '{':
				goto yy108;

			case '~':
				goto yy110;

			default:
				goto yy58;
		}

yy58: {
			return TEXT_BRACE_LEFT;
		}
yy59:
		++YYCURSOR;
		yych = *YYCURSOR;
		goto yy105;
yy60: {
			return PIPE;
		}
yy61:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '}':
				goto yy102;

			default:
				goto yy62;
		}

yy62: {
			return TEXT_BRACE_RIGHT;
		}
yy63:
		yyaccept = 8;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '>':
				goto yy98;

			case '~':
				goto yy97;

			default:
				goto yy64;
		}

yy64: {
			return SUBSCRIPT;
		}
yy65:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0xA0:
				goto yy71;

			default:
				goto yy3;
		}

yy66:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 0xBF:
				goto yy67;

			default:
				goto yy3;
		}

yy67:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xBC:
				goto yy69;

			default:
				goto yy68;
		}

yy68:
		YYCURSOR = YYMARKER;

		switch (yyaccept) {
			case 0:
				goto yy7;

			case 1:
				goto yy3;

			case 2:
				goto yy14;

			case 3:
				goto yy20;

			case 4:
				goto yy30;

			case 5:
				goto yy40;

			case 6:
				goto yy42;

			case 7:
				goto yy58;

			case 8:
				goto yy64;

			case 9:
				goto yy73;

			case 10:
				goto yy80;

			case 11:
				goto yy92;

			case 12:
				goto yy109;

			case 13:
				goto yy243;

			case 14:
				goto yy293;

			case 15:
				goto yy300;

			case 16:
				goto yy309;

			case 17:
				goto yy316;

			case 18:
				goto yy325;

			default:
				goto yy332;
		}

yy69:
		++YYCURSOR;
		{
			return TEXT_REPLACEMENT_CHAR;
		}
yy71:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case '\t':
				goto yy75;

			case ' ':
				goto yy72;

			case 0xC2:
				goto yy74;

			default:
				goto yy68;
		}

yy72:
		yyaccept = 9;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy79;

			case '\r':
				goto yy81;

			case ' ':
				goto yy77;

			case 0xC2:
				goto yy78;

			default:
				goto yy73;
		}

yy73: {
			return NON_INDENT_SPACE;
		}
yy74:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy72;

			default:
				goto yy68;
		}

yy75:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return NON_INDENT_SPACE;
		}
yy77:
		yyaccept = 9;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy79;

			case '\r':
				goto yy81;

			case ' ':
				goto yy91;

			case 0xC2:
				goto yy93;

			default:
				goto yy73;
		}

yy78:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy77;

			default:
				goto yy68;
		}

yy79:
		yyaccept = 10;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy82;

			default:
				goto yy80;
		}

yy80: {
			return TEXT_LINEBREAK;
		}
yy81:
		yyaccept = 10;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy79;

			case ' ':
				goto yy82;

			default:
				goto yy80;
		}

yy82:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\v':
			case '\f':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				goto yy83;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				goto yy85;

			case 0xE0:
				goto yy86;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				goto yy87;

			case 0xF0:
				goto yy88;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				goto yy89;

			case 0xF4:
				goto yy90;

			default:
				goto yy68;
		}

yy83:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_LINEBREAK_SP;
		}
yy85:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy83;

			default:
				goto yy68;
		}

yy86:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy85;

			default:
				goto yy68;
		}

yy87:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy85;

			default:
				goto yy68;
		}

yy88:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy87;

			default:
				goto yy68;
		}

yy89:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy87;

			default:
				goto yy68;
		}

yy90:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy87;

			default:
				goto yy68;
		}

yy91:
		yyaccept = 11;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case '\n':
				goto yy79;

			case '\r':
				goto yy81;

			case ' ':
				goto yy94;

			case 0xC2:
				goto yy96;

			default:
				goto yy92;
		}

yy92: {
			return INDENT_SPACE;
		}
yy93:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy91;

			default:
				goto yy68;
		}

yy94:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy79;

			case '\r':
				goto yy81;

			case ' ':
				goto yy94;

			case 0xC2:
				goto yy96;

			default:
				goto yy68;
		}

yy96:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy94;

			default:
				goto yy68;
		}

yy97:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy100;

			default:
				goto yy68;
		}

yy98:
		++YYCURSOR;
		{
			return CRITIC_SUB_DIV;
		}
yy100:
		++YYCURSOR;
		{
			return CRITIC_SUB_CLOSE;
		}
yy102:
		++YYCURSOR;
		{
			return BRACE_DOUBLE_RIGHT;
		}
yy104:
		++YYCURSOR;
		yych = *YYCURSOR;
yy105:

		switch (yych) {
			case '|':
				goto yy104;

			default:
				goto yy60;
		}

yy106:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '=':
				goto yy138;

			default:
				goto yy107;
		}

yy107: {
			return RAW_FILTER_LEFT;
		}
yy108:
		yyaccept = 12;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case 'T':
				goto yy122;

			default:
				goto yy109;
		}

yy109: {
			return BRACE_DOUBLE_LEFT;
		}
yy110:
		yych = *++YYCURSOR;

		switch (yych) {
			case '~':
				goto yy120;

			default:
				goto yy68;
		}

yy111:
		yych = *++YYCURSOR;

		switch (yych) {
			case '>':
				goto yy118;

			default:
				goto yy68;
		}

yy112:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy116;

			default:
				goto yy68;
		}

yy113:
		yych = *++YYCURSOR;

		switch (yych) {
			case '+':
				goto yy114;

			default:
				goto yy68;
		}

yy114:
		++YYCURSOR;
		{
			return CRITIC_ADD_OPEN;
		}
yy116:
		++YYCURSOR;
		{
			return CRITIC_DEL_OPEN;
		}
yy118:
		++YYCURSOR;
		{
			return CRITIC_COM_OPEN;
		}
yy120:
		++YYCURSOR;
		{
			return CRITIC_SUB_OPEN;
		}
yy122:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'O':
				goto yy123;

			default:
				goto yy68;
		}

yy123:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'C':
				goto yy124;

			default:
				goto yy68;
		}

yy124:
		yych = *++YYCURSOR;

		switch (yych) {
			case ':':
				goto yy125;

			case '}':
				goto yy126;

			default:
				goto yy68;
		}

yy125:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy129;

			default:
				goto yy68;
		}

yy126:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy127;

			default:
				goto yy68;
		}

yy127:
		++YYCURSOR;
		{
			return TOC;
		}
yy129:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy130;

			case '}':
				goto yy131;

			default:
				goto yy68;
		}

yy130:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy134;

			default:
				goto yy68;
		}

yy131:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy132;

			default:
				goto yy68;
		}

yy132:
		++YYCURSOR;
		{
			return TOC_SINGLE;
		}
yy134:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy135;

			default:
				goto yy68;
		}

yy135:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy136;

			default:
				goto yy68;
		}

yy136:
		++YYCURSOR;
		{
			return TOC_RANGE;
		}
yy138:
		++YYCURSOR;
		{
			return CRITIC_HI_OPEN;
		}
yy140:
		++YYCURSOR;
		yych = *YYCURSOR;
yy141:

		switch (yych) {
			case '`':
				goto yy140;

			default:
				goto yy56;
		}

yy142:
		++YYCURSOR;
yy143: {
			return TEXT_LINEBREAK;
		}
yy144:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy142;

			default:
				goto yy143;
		}

yy145:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '(':
				goto yy211;

			case ')':
				goto yy213;

			case '[':
				goto yy215;

			case ']':
				goto yy217;

			default:
				goto yy146;
		}

yy146: {
			return ESCAPED_CHARACTER;
		}
yy147:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy149:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy151:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy153:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy155:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy157:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy159:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy161:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy163:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy165:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy167:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy169:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy171:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy173:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy175:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy177:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy179:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy181:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy183:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy185:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy187:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy189:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy191:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy193:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy195:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy197:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy199:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy201:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy203:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy205:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy207:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy209:
		++YYCURSOR;
		{
			return ESCAPED_CHARACTER;
		}
yy211:
		++YYCURSOR;
		{
			return MATH_PAREN_OPEN;
		}
yy213:
		++YYCURSOR;
		{
			return MATH_PAREN_CLOSE;
		}
yy215:
		++YYCURSOR;
		{
			return MATH_BRACKET_OPEN;
		}
yy217:
		++YYCURSOR;
		{
			return MATH_BRACKET_CLOSE;
		}
yy219:
		++YYCURSOR;
		{
			return BRACKET_VARIABLE_LEFT;
		}
yy221:
		++YYCURSOR;
		{
			return BRACKET_GLOSSARY_LEFT;
		}
yy223:
		++YYCURSOR;
		{
			return BRACKET_FOOTNOTE_LEFT;
		}
yy225:
		++YYCURSOR;
		{
			return BRACKET_CITATION_LEFT;
		}
yy227:
		++YYCURSOR;
		{
			return BRACKET_ABBREVIATION_LEFT;
		}
yy229:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy230;

			default:
				goto yy68;
		}

yy230:
		++YYCURSOR;
		{
			return CRITIC_HI_CLOSE;
		}
yy232:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy236;

			default:
				goto yy68;
		}

yy233:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy234;

			default:
				goto yy68;
		}

yy234:
		++YYCURSOR;
		{
			return CRITIC_COM_CLOSE;
		}
yy236:
		yych = *++YYCURSOR;

		switch (yych) {
			case '-':
				goto yy237;

			default:
				goto yy68;
		}

yy237:
		++YYCURSOR;
		{
			return HTML_COMMENT_START;
		}
yy239:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case '\t':
			case ' ':
				goto yy245;

			case '\n':
				goto yy242;

			case '\r':
				goto yy244;

			case 0xC2:
				goto yy247;

			default:
				goto yy68;
		}

yy240:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '.':
				goto yy239;

			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy240;

			default:
				goto yy68;
		}

yy242:
		++YYCURSOR;
yy243:
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_NUMBER_POSS_LIST;
		}
yy244:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy242;

			default:
				goto yy243;
		}

yy245:
		yyaccept = 13;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '\t':
			case ' ':
				goto yy245;

			case 0xC2:
				goto yy247;

			default:
				goto yy243;
		}

yy247:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy245;

			default:
				goto yy68;
		}

yy248:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy252;

			default:
				goto yy68;
		}

yy249:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy250;

			default:
				goto yy68;
		}

yy250:
		++YYCURSOR;
		{
			return ELLIPSIS;
		}
yy252:
		yych = *++YYCURSOR;

		switch (yych) {
			case ' ':
				goto yy253;

			default:
				goto yy68;
		}

yy253:
		yych = *++YYCURSOR;

		switch (yych) {
			case '.':
				goto yy254;

			default:
				goto yy68;
		}

yy254:
		++YYCURSOR;
		{
			return ELLIPSIS;
		}
yy256:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case '-':
				goto yy262;

			case '>':
				goto yy260;

			case '}':
				goto yy258;

			default:
				goto yy257;
		}

yy257: {
			return DASH_N;
		}
yy258:
		++YYCURSOR;
		{
			return CRITIC_DEL_CLOSE;
		}
yy260:
		++YYCURSOR;
		{
			return HTML_COMMENT_STOP;
		}
yy262:
		++YYCURSOR;
		{
			return DASH_M;
		}
yy264:
		yych = *++YYCURSOR;

		switch (yych) {
			case '}':
				goto yy265;

			default:
				goto yy68;
		}

yy265:
		++YYCURSOR;
		{
			return CRITIC_ADD_CLOSE;
		}
yy267:
		++YYCURSOR;
		{
			return QUOTE_RIGHT_ALT;
		}
yy269:
		++YYCURSOR;
		yych = *YYCURSOR;
yy270:

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
				goto yy269;

			case ';':
				goto yy283;

			default:
				goto yy68;
		}

yy271:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'M':
			case 'm':
				goto yy282;

			default:
				goto yy270;
		}

yy272:
		yych = *++YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy274;

			case 'X':
			case 'x':
				goto yy273;

			default:
				goto yy68;
		}

yy273:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy68;

			default:
				goto yy279;
		}

yy274:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				goto yy274;

			case ';':
				goto yy276;

			default:
				goto yy68;
		}

yy276:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy278:
		++YYCURSOR;
		yych = *YYCURSOR;
yy279:

		switch (yych) {
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
				goto yy278;

			case ';':
				goto yy280;

			default:
				goto yy68;
		}

yy280:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy282:
		yych = *++YYCURSOR;

		switch (yych) {
			case 'P':
			case 'p':
				goto yy285;

			default:
				goto yy270;
		}

yy283:
		++YYCURSOR;
		{
			return HTML_ENTITY;
		}
yy285:
		yych = *++YYCURSOR;

		switch (yych) {
			case ';':
				goto yy286;

			default:
				goto yy270;
		}

yy286:
		++YYCURSOR;
		{
			return AMPERSAND_LONG;
		}
yy288:
		++YYCURSOR;
		{
			return MATH_DOLLAR_DOUBLE;
		}
yy290:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\t':
			case '\n':
			case '\r':
			case ' ':
			case 0xC2:
				goto yy299;

			case '#':
				goto yy305;

			default:
				goto yy68;
		}

yy291:
		yyaccept = 14;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy292:

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy295;

			case '\t':
			case ' ':
				goto yy291;

			case '\r':
				goto yy297;

			case 0xC2:
				goto yy294;

			default:
				goto yy293;
		}

yy293: {
			return HASH1;
		}
yy294:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy291;

			default:
				goto yy68;
		}

yy295:
		++YYCURSOR;
yy296:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH1;
		}
yy297:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy295;

			default:
				goto yy296;
		}

yy298:
		yyaccept = 15;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy299:

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy302;

			case '\t':
			case ' ':
				goto yy298;

			case '\r':
				goto yy304;

			case 0xC2:
				goto yy301;

			default:
				goto yy300;
		}

yy300: {
			return HASH2;
		}
yy301:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy298;

			default:
				goto yy68;
		}

yy302:
		++YYCURSOR;
yy303:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH2;
		}
yy304:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy302;

			default:
				goto yy303;
		}

yy305:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\t':
			case '\n':
			case '\r':
			case ' ':
			case 0xC2:
				goto yy308;

			case '#':
				goto yy306;

			default:
				goto yy68;
		}

yy306:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\t':
			case '\n':
			case '\r':
			case ' ':
			case 0xC2:
				goto yy315;

			case '#':
				goto yy321;

			default:
				goto yy68;
		}

yy307:
		yyaccept = 16;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy308:

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy311;

			case '\t':
			case ' ':
				goto yy307;

			case '\r':
				goto yy313;

			case 0xC2:
				goto yy310;

			default:
				goto yy309;
		}

yy309: {
			return HASH3;
		}
yy310:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy307;

			default:
				goto yy68;
		}

yy311:
		++YYCURSOR;
yy312:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH3;
		}
yy313:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy311;

			default:
				goto yy312;
		}

yy314:
		yyaccept = 17;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy315:

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy318;

			case '\t':
			case ' ':
				goto yy314;

			case '\r':
				goto yy320;

			case 0xC2:
				goto yy317;

			default:
				goto yy316;
		}

yy316: {
			return HASH4;
		}
yy317:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy314;

			default:
				goto yy68;
		}

yy318:
		++YYCURSOR;
yy319:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH4;
		}
yy320:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy318;

			default:
				goto yy319;
		}

yy321:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\t':
			case '\n':
			case '\r':
			case ' ':
			case 0xC2:
				goto yy324;

			case '#':
				goto yy322;

			default:
				goto yy68;
		}

yy322:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case '\t':
			case '\n':
			case '\r':
			case ' ':
			case 0xC2:
				goto yy331;

			default:
				goto yy68;
		}

yy323:
		yyaccept = 18;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy324:

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy327;

			case '\t':
			case ' ':
				goto yy323;

			case '\r':
				goto yy329;

			case 0xC2:
				goto yy326;

			default:
				goto yy325;
		}

yy325: {
			return HASH5;
		}
yy326:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy323;

			default:
				goto yy68;
		}

yy327:
		++YYCURSOR;
yy328:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH5;
		}
yy329:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy327;

			default:
				goto yy328;
		}

yy330:
		yyaccept = 19;
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
yy331:

		switch (yych) {
			case 0x00:
			case '\n':
				goto yy334;

			case '\t':
			case ' ':
				goto yy330;

			case '\r':
				goto yy336;

			case 0xC2:
				goto yy333;

			default:
				goto yy332;
		}

yy332: {
			return HASH6;
		}
yy333:
		++YYCURSOR;
		yych = *YYCURSOR;

		switch (yych) {
			case 0xA0:
				goto yy330;

			default:
				goto yy68;
		}

yy334:
		++YYCURSOR;
yy335:
		YYCURSOR = YYCTXMARKER;
		{
			return HASH6;
		}
yy336:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy334;

			default:
				goto yy335;
		}

yy337:
		++YYCURSOR;
		{
			return BRACKET_IMAGE_LEFT;
		}
yy339:
		yych = *++YYCURSOR;
		goto yy7;
yy340:
		yych = *++YYCURSOR;

		switch (yych) {
			case '\n':
				goto yy339;

			default:
				goto yy7;
		}

yy341:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);

		switch (yych) {
			case ' ':
				goto yy342;

			default:
				goto yy7;
		}

yy342:
		yych = *++YYCURSOR;
		YYCTXMARKER = YYCURSOR;

		switch (yych) {
			case 0x00:
			case 0x01:
			case 0x02:
			case 0x03:
			case 0x04:
			case 0x05:
			case 0x06:
			case 0x07:
			case 0x08:
			case '\v':
			case '\f':
			case 0x0E:
			case 0x0F:
			case 0x10:
			case 0x11:
			case 0x12:
			case 0x13:
			case 0x14:
			case 0x15:
			case 0x16:
			case 0x17:
			case 0x18:
			case 0x19:
			case 0x1A:
			case 0x1B:
			case 0x1C:
			case 0x1D:
			case 0x1E:
			case 0x1F:
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '/':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case 0x7F:
				goto yy343;

			case 0xC2:
			case 0xC3:
			case 0xC4:
			case 0xC5:
			case 0xC6:
			case 0xC7:
			case 0xC8:
			case 0xC9:
			case 0xCA:
			case 0xCB:
			case 0xCC:
			case 0xCD:
			case 0xCE:
			case 0xCF:
			case 0xD0:
			case 0xD1:
			case 0xD2:
			case 0xD3:
			case 0xD4:
			case 0xD5:
			case 0xD6:
			case 0xD7:
			case 0xD8:
			case 0xD9:
			case 0xDA:
			case 0xDB:
			case 0xDC:
			case 0xDD:
			case 0xDE:
			case 0xDF:
				goto yy345;

			case 0xE0:
				goto yy346;

			case 0xE1:
			case 0xE2:
			case 0xE3:
			case 0xE4:
			case 0xE5:
			case 0xE6:
			case 0xE7:
			case 0xE8:
			case 0xE9:
			case 0xEA:
			case 0xEB:
			case 0xEC:
			case 0xED:
			case 0xEE:
			case 0xEF:
				goto yy347;

			case 0xF0:
				goto yy348;

			case 0xF1:
			case 0xF2:
			case 0xF3:
				goto yy349;

			case 0xF4:
				goto yy350;

			default:
				goto yy68;
		}

yy343:
		++YYCURSOR;
		YYCURSOR = YYCTXMARKER;
		{
			return TEXT_NL_SP;
		}
yy345:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy343;

			default:
				goto yy68;
		}

yy346:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy345;

			default:
				goto yy68;
		}

yy347:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy345;

			default:
				goto yy68;
		}

yy348:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy347;

			default:
				goto yy68;
		}

yy349:
		yych = *++YYCURSOR;

		switch (yych) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9A:
			case 0x9B:
			case 0x9C:
			case 0x9D:
			case 0x9E:
			case 0x9F:
			case 0xA0:
			case 0xA1:
			case 0xA2:
			case 0xA3:
			case 0xA4:
			case 0xA5:
			case 0xA6:
			case 0xA7:
			case 0xA8:
			case 0xA9:
			case 0xAA:
			case 0xAB:
			case 0xAC:
			case 0xAD:
			case 0xAE:
			case 0xAF:
			case 0xB0:
			case 0xB1:
			case 0xB2:
			case 0xB3:
			case 0xB4:
			case 0xB5:
			case 0xB6:
			case 0xB7:
			case 0xB8:
			case 0xB9:
			case 0xBA:
			case 0xBB:
			case 0xBC:
			case 0xBD:
			case 0xBE:
			case 0xBF:
				goto yy347;

			default:
				goto yy68;
		}

yy350:
		++YYCURSOR;

		switch ((yych = *YYCURSOR)) {
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8A:
			case 0x8B:
			case 0x8C:
			case 0x8D:
			case 0x8E:
			case 0x8F:
				goto yy347;

			default:
				goto yy68;
		}
	}

}
