#define LINE_CONTINUATION                1
#define LINE_PLAIN                       2
#define LINE_INDENTED_TAB                3
#define LINE_INDENTED_SPACE              4
#define LINE_ATX_1                       5
#define LINE_ATX_2                       6
#define LINE_ATX_3                       7
#define LINE_ATX_4                       8
#define LINE_ATX_5                       9
#define LINE_ATX_6                      10
#define LINE_HR                         11
#define LINE_EMPTY                      12
#define LINE_BLOCKQUOTE                 13
#define LINE_LIST_BULLETED              14
#define LINE_LIST_ENUMERATED            15
#define LINE_TABLE                      16
#define LINE_DEF_CITATION               17
#define LINE_DEF_FOOTNOTE               18
#define LINE_DEF_LINK                   19
#define LINE_HTML                       20
#define LINE_FENCE_BACKTICK             21
#define LINE_FENCE_BACKTICK_START       22
