#define LINE_HR                          1
#define LINE_SETEXT_1                    2
#define LINE_SETEXT_2                    3
#define LINE_YAML                        4
#define LINE_CONTINUATION                5
#define LINE_PLAIN                       6
#define LINE_INDENTED_TAB                7
#define LINE_INDENTED_SPACE              8
#define LINE_TABLE                       9
#define LINE_TABLE_SEPARATOR            10
#define LINE_FALLBACK                   11
#define LINE_HTML                       12
#define LINE_ATX_1                      13
#define LINE_ATX_2                      14
#define LINE_ATX_3                      15
#define LINE_ATX_4                      16
#define LINE_ATX_5                      17
#define LINE_ATX_6                      18
#define LINE_BLOCKQUOTE                 19
#define LINE_LIST_BULLETED              20
#define LINE_LIST_ENUMERATED            21
#define LINE_DEF_ABBREVIATION           22
#define LINE_DEF_CITATION               23
#define LINE_DEF_FOOTNOTE               24
#define LINE_DEF_GLOSSARY               25
#define LINE_DEF_LINK                   26
#define LINE_TOC                        27
#define LINE_DEFINITION                 28
#define LINE_META                       29
#define LINE_BACKTICK                   30
#define LINE_FENCE_BACKTICK_3           31
#define LINE_FENCE_BACKTICK_4           32
#define LINE_FENCE_BACKTICK_5           33
#define LINE_FENCE_BACKTICK_START_3     34
#define LINE_FENCE_BACKTICK_START_4     35
#define LINE_FENCE_BACKTICK_START_5     36
#define LINE_STOP_COMMENT               37
#define LINE_EMPTY                      38
#define LINE_START_COMMENT              39
