#define LINE_PLAIN                       1
#define LINE_TABLE_SEPARATOR             2
#define LINE_CONTINUATION                3
#define LINE_INDENTED_TAB                4
#define LINE_INDENTED_SPACE              5
#define LINE_HTML                        6
#define LINE_ATX_1                       7
#define LINE_ATX_2                       8
#define LINE_ATX_3                       9
#define LINE_ATX_4                      10
#define LINE_ATX_5                      11
#define LINE_ATX_6                      12
#define LINE_HR                         13
#define LINE_BLOCKQUOTE                 14
#define LINE_LIST_BULLETED              15
#define LINE_LIST_ENUMERATED            16
#define LINE_TABLE                      17
#define LINE_DEF_CITATION               18
#define LINE_DEF_FOOTNOTE               19
#define LINE_DEF_LINK                   20
#define LINE_FENCE_BACKTICK             21
#define LINE_FENCE_BACKTICK_START       22
#define LINE_TOC                        23
#define LINE_EMPTY                      24
#define LINE_META                       25
#define LINE_DEFINITION                 26
